//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace FancyFix.OA.Model
{

	/// <summary>
	/// 实体类Design_DetailType 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Design_DetailType")]
	[Serializable]
	public partial class Design_DetailType : Entity 
	{
		#region Model
		private int _Id;
		private int? _ClassId;
		private int? _Display;
		private string _Name;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ClassId
		{
			get{ return _ClassId; }
			set
			{
				this.OnPropertyValueChange(_.ClassId,_ClassId,value);
				this._ClassId=value;
			}
		}
		/// <summary>
		/// 是否显示；1显示，2不显示
		/// </summary>
		public int? Display
		{
			get{ return _Display; }
			set
			{
				this.OnPropertyValueChange(_.Display,_Display,value);
				this._Display=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.ClassId,
				_.Display,
				_.Name};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._ClassId,
				this._Display,
				this._Name};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Design_DetailType");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Design_DetailType","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ClassId = new Field("ClassId","Design_DetailType","ClassId");
			/// <summary>
			/// 是否显示；1显示，2不显示
			/// </summary>
			public readonly static Field Display = new Field("Display","Design_DetailType","是否显示；1显示，2不显示");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name","Design_DetailType","Name");
		}
		#endregion


	}
}

