//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace FancyFix.OA.Model
{

	/// <summary>
	/// 实体类Finance_EveryDaySaleLog 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Finance_EveryDaySaleLog")]
	[Serializable]
	public partial class Finance_EveryDaySaleLog : Entity 
	{
		#region Model
		private int _Id;
		private DateTime? _SaleDate;
		private int? _Year;
		private int? _Month;
		private int? _Day;
		private string _DepartmentName;
		private string _SaleName;
		private string _Customer;
		private string _ContractNumber;
		private string _ProductName;
		private string _ProductSKU;
		private decimal? _SaleCount;
		private decimal? _SalePrice;
		private string _Currency;
		private decimal? _ExchangeRate;
		private decimal? _SaleIncome;
		private decimal? _MaterialUnitPrice;
		private decimal? _ProcessUnitPrice;
		private decimal? _MaterialTotalPrice;
		private decimal? _ProcessTotalPrice;
		private decimal? _GrossProfit;
		private decimal? _GrossProfitRate;
		private decimal? _ChangeCostNumber;
		private decimal? _ChangeCostMatter;
		private decimal? _ContributionMoney;
		private decimal? _ContributionRatio;
		private decimal? _AvgCoatUndue;
		private decimal? _AvgCoatCurrentdue;
		private decimal? _AvgCoatOverdue;
		private decimal? _CustomerContributionMoney;
		private decimal? _CustomerContributionRatio;
		private bool? _Follow;
		private DateTime? _AddDate;
		private int? _AddUserId;
		private DateTime? _LastDate;
		private int? _LastUserId;
		private int? _Display;
		private string _ProductSpecification;
		private string _Supplier;
		private string _SPU;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 销售日期
		/// </summary>
		public DateTime? SaleDate
		{
			get{ return _SaleDate; }
			set
			{
				this.OnPropertyValueChange(_.SaleDate,_SaleDate,value);
				this._SaleDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Year
		{
			get{ return _Year; }
			set
			{
				this.OnPropertyValueChange(_.Year,_Year,value);
				this._Year=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Month
		{
			get{ return _Month; }
			set
			{
				this.OnPropertyValueChange(_.Month,_Month,value);
				this._Month=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Day
		{
			get{ return _Day; }
			set
			{
				this.OnPropertyValueChange(_.Day,_Day,value);
				this._Day=value;
			}
		}
		/// <summary>
		/// 部门
		/// </summary>
		public string DepartmentName
		{
			get{ return _DepartmentName; }
			set
			{
				this.OnPropertyValueChange(_.DepartmentName,_DepartmentName,value);
				this._DepartmentName=value;
			}
		}
		/// <summary>
		/// 销售员
		/// </summary>
		public string SaleName
		{
			get{ return _SaleName; }
			set
			{
				this.OnPropertyValueChange(_.SaleName,_SaleName,value);
				this._SaleName=value;
			}
		}
		/// <summary>
		/// 客户/店铺
		/// </summary>
		public string Customer
		{
			get{ return _Customer; }
			set
			{
				this.OnPropertyValueChange(_.Customer,_Customer,value);
				this._Customer=value;
			}
		}
		/// <summary>
		/// 合同号
		/// </summary>
		public string ContractNumber
		{
			get{ return _ContractNumber; }
			set
			{
				this.OnPropertyValueChange(_.ContractNumber,_ContractNumber,value);
				this._ContractNumber=value;
			}
		}
		/// <summary>
		/// 产品名称
		/// </summary>
		public string ProductName
		{
			get{ return _ProductName; }
			set
			{
				this.OnPropertyValueChange(_.ProductName,_ProductName,value);
				this._ProductName=value;
			}
		}
		/// <summary>
		/// 产品SKU
		/// </summary>
		public string ProductSKU
		{
			get{ return _ProductSKU; }
			set
			{
				this.OnPropertyValueChange(_.ProductSKU,_ProductSKU,value);
				this._ProductSKU=value;
			}
		}
		/// <summary>
		/// 销售数量
		/// </summary>
		public decimal? SaleCount
		{
			get{ return _SaleCount; }
			set
			{
				this.OnPropertyValueChange(_.SaleCount,_SaleCount,value);
				this._SaleCount=value;
			}
		}
		/// <summary>
		/// 销售单价
		/// </summary>
		public decimal? SalePrice
		{
			get{ return _SalePrice; }
			set
			{
				this.OnPropertyValueChange(_.SalePrice,_SalePrice,value);
				this._SalePrice=value;
			}
		}
		/// <summary>
		/// 货币种类
		/// </summary>
		public string Currency
		{
			get{ return _Currency; }
			set
			{
				this.OnPropertyValueChange(_.Currency,_Currency,value);
				this._Currency=value;
			}
		}
		/// <summary>
		/// 汇率
		/// </summary>
		public decimal? ExchangeRate
		{
			get{ return _ExchangeRate; }
			set
			{
				this.OnPropertyValueChange(_.ExchangeRate,_ExchangeRate,value);
				this._ExchangeRate=value;
			}
		}
		/// <summary>
		/// 销售收入
		/// </summary>
		public decimal? SaleIncome
		{
			get{ return _SaleIncome; }
			set
			{
				this.OnPropertyValueChange(_.SaleIncome,_SaleIncome,value);
				this._SaleIncome=value;
			}
		}
		/// <summary>
		/// 材料单价
		/// </summary>
		public decimal? MaterialUnitPrice
		{
			get{ return _MaterialUnitPrice; }
			set
			{
				this.OnPropertyValueChange(_.MaterialUnitPrice,_MaterialUnitPrice,value);
				this._MaterialUnitPrice=value;
			}
		}
		/// <summary>
		/// 加工费单价
		/// </summary>
		public decimal? ProcessUnitPrice
		{
			get{ return _ProcessUnitPrice; }
			set
			{
				this.OnPropertyValueChange(_.ProcessUnitPrice,_ProcessUnitPrice,value);
				this._ProcessUnitPrice=value;
			}
		}
		/// <summary>
		/// 材料总价
		/// </summary>
		public decimal? MaterialTotalPrice
		{
			get{ return _MaterialTotalPrice; }
			set
			{
				this.OnPropertyValueChange(_.MaterialTotalPrice,_MaterialTotalPrice,value);
				this._MaterialTotalPrice=value;
			}
		}
		/// <summary>
		/// 加工费总价
		/// </summary>
		public decimal? ProcessTotalPrice
		{
			get{ return _ProcessTotalPrice; }
			set
			{
				this.OnPropertyValueChange(_.ProcessTotalPrice,_ProcessTotalPrice,value);
				this._ProcessTotalPrice=value;
			}
		}
		/// <summary>
		/// 毛利额
		/// </summary>
		public decimal? GrossProfit
		{
			get{ return _GrossProfit; }
			set
			{
				this.OnPropertyValueChange(_.GrossProfit,_GrossProfit,value);
				this._GrossProfit=value;
			}
		}
		/// <summary>
		/// 毛利率
		/// </summary>
		public decimal? GrossProfitRate
		{
			get{ return _GrossProfitRate; }
			set
			{
				this.OnPropertyValueChange(_.GrossProfitRate,_GrossProfitRate,value);
				this._GrossProfitRate=value;
			}
		}
		/// <summary>
		/// 变动费用量
		/// </summary>
		public decimal? ChangeCostNumber
		{
			get{ return _ChangeCostNumber; }
			set
			{
				this.OnPropertyValueChange(_.ChangeCostNumber,_ChangeCostNumber,value);
				this._ChangeCostNumber=value;
			}
		}
		/// <summary>
		/// 变动费用事
		/// </summary>
		public decimal? ChangeCostMatter
		{
			get{ return _ChangeCostMatter; }
			set
			{
				this.OnPropertyValueChange(_.ChangeCostMatter,_ChangeCostMatter,value);
				this._ChangeCostMatter=value;
			}
		}
		/// <summary>
		/// 经营贡献金额
		/// </summary>
		public decimal? ContributionMoney
		{
			get{ return _ContributionMoney; }
			set
			{
				this.OnPropertyValueChange(_.ContributionMoney,_ContributionMoney,value);
				this._ContributionMoney=value;
			}
		}
		/// <summary>
		/// 贡献比例
		/// </summary>
		public decimal? ContributionRatio
		{
			get{ return _ContributionRatio; }
			set
			{
				this.OnPropertyValueChange(_.ContributionRatio,_ContributionRatio,value);
				this._ContributionRatio=value;
			}
		}
		/// <summary>
		/// 应收账款平均资金成本_未到期
		/// </summary>
		public decimal? AvgCoatUndue
		{
			get{ return _AvgCoatUndue; }
			set
			{
				this.OnPropertyValueChange(_.AvgCoatUndue,_AvgCoatUndue,value);
				this._AvgCoatUndue=value;
			}
		}
		/// <summary>
		/// 应收账款平均资金成本_当期
		/// </summary>
		public decimal? AvgCoatCurrentdue
		{
			get{ return _AvgCoatCurrentdue; }
			set
			{
				this.OnPropertyValueChange(_.AvgCoatCurrentdue,_AvgCoatCurrentdue,value);
				this._AvgCoatCurrentdue=value;
			}
		}
		/// <summary>
		/// 应收账款平均资金成本_逾期
		/// </summary>
		public decimal? AvgCoatOverdue
		{
			get{ return _AvgCoatOverdue; }
			set
			{
				this.OnPropertyValueChange(_.AvgCoatOverdue,_AvgCoatOverdue,value);
				this._AvgCoatOverdue=value;
			}
		}
		/// <summary>
		/// 客户净贡献_金额
		/// </summary>
		public decimal? CustomerContributionMoney
		{
			get{ return _CustomerContributionMoney; }
			set
			{
				this.OnPropertyValueChange(_.CustomerContributionMoney,_CustomerContributionMoney,value);
				this._CustomerContributionMoney=value;
			}
		}
		/// <summary>
		/// 客户净贡献_比例
		/// </summary>
		public decimal? CustomerContributionRatio
		{
			get{ return _CustomerContributionRatio; }
			set
			{
				this.OnPropertyValueChange(_.CustomerContributionRatio,_CustomerContributionRatio,value);
				this._CustomerContributionRatio=value;
			}
		}
		/// <summary>
		/// 是否关注
		/// </summary>
		public bool? Follow
		{
			get{ return _Follow; }
			set
			{
				this.OnPropertyValueChange(_.Follow,_Follow,value);
				this._Follow=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? AddDate
		{
			get{ return _AddDate; }
			set
			{
				this.OnPropertyValueChange(_.AddDate,_AddDate,value);
				this._AddDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? AddUserId
		{
			get{ return _AddUserId; }
			set
			{
				this.OnPropertyValueChange(_.AddUserId,_AddUserId,value);
				this._AddUserId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? LastDate
		{
			get{ return _LastDate; }
			set
			{
				this.OnPropertyValueChange(_.LastDate,_LastDate,value);
				this._LastDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? LastUserId
		{
			get{ return _LastUserId; }
			set
			{
				this.OnPropertyValueChange(_.LastUserId,_LastUserId,value);
				this._LastUserId=value;
			}
		}
		/// <summary>
		/// _1：显示，2：隐藏
		/// </summary>
		public int? Display
		{
			get{ return _Display; }
			set
			{
				this.OnPropertyValueChange(_.Display,_Display,value);
				this._Display=value;
			}
		}
		/// <summary>
		/// 产品规格
		/// </summary>
		public string ProductSpecification
		{
			get{ return _ProductSpecification; }
			set
			{
				this.OnPropertyValueChange(_.ProductSpecification,_ProductSpecification,value);
				this._ProductSpecification=value;
			}
		}
		/// <summary>
		/// 供应商
		/// </summary>
		public string Supplier
		{
			get{ return _Supplier; }
			set
			{
				this.OnPropertyValueChange(_.Supplier,_Supplier,value);
				this._Supplier=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SPU
		{
			get{ return _SPU; }
			set
			{
				this.OnPropertyValueChange(_.SPU,_SPU,value);
				this._SPU=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.SaleDate,
				_.Year,
				_.Month,
				_.Day,
				_.DepartmentName,
				_.SaleName,
				_.Customer,
				_.ContractNumber,
				_.ProductName,
				_.ProductSKU,
				_.SaleCount,
				_.SalePrice,
				_.Currency,
				_.ExchangeRate,
				_.SaleIncome,
				_.MaterialUnitPrice,
				_.ProcessUnitPrice,
				_.MaterialTotalPrice,
				_.ProcessTotalPrice,
				_.GrossProfit,
				_.GrossProfitRate,
				_.ChangeCostNumber,
				_.ChangeCostMatter,
				_.ContributionMoney,
				_.ContributionRatio,
				_.AvgCoatUndue,
				_.AvgCoatCurrentdue,
				_.AvgCoatOverdue,
				_.CustomerContributionMoney,
				_.CustomerContributionRatio,
				_.Follow,
				_.AddDate,
				_.AddUserId,
				_.LastDate,
				_.LastUserId,
				_.Display,
				_.ProductSpecification,
				_.Supplier,
				_.SPU};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._SaleDate,
				this._Year,
				this._Month,
				this._Day,
				this._DepartmentName,
				this._SaleName,
				this._Customer,
				this._ContractNumber,
				this._ProductName,
				this._ProductSKU,
				this._SaleCount,
				this._SalePrice,
				this._Currency,
				this._ExchangeRate,
				this._SaleIncome,
				this._MaterialUnitPrice,
				this._ProcessUnitPrice,
				this._MaterialTotalPrice,
				this._ProcessTotalPrice,
				this._GrossProfit,
				this._GrossProfitRate,
				this._ChangeCostNumber,
				this._ChangeCostMatter,
				this._ContributionMoney,
				this._ContributionRatio,
				this._AvgCoatUndue,
				this._AvgCoatCurrentdue,
				this._AvgCoatOverdue,
				this._CustomerContributionMoney,
				this._CustomerContributionRatio,
				this._Follow,
				this._AddDate,
				this._AddUserId,
				this._LastDate,
				this._LastUserId,
				this._Display,
				this._ProductSpecification,
				this._Supplier,
				this._SPU};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Finance_EveryDaySaleLog");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Finance_EveryDaySaleLog","Id");
			/// <summary>
			/// 销售日期
			/// </summary>
			public readonly static Field SaleDate = new Field("SaleDate","Finance_EveryDaySaleLog","销售日期");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Year = new Field("Year","Finance_EveryDaySaleLog","Year");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Month = new Field("Month","Finance_EveryDaySaleLog","Month");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Day = new Field("Day","Finance_EveryDaySaleLog","Day");
			/// <summary>
			/// 部门
			/// </summary>
			public readonly static Field DepartmentName = new Field("DepartmentName","Finance_EveryDaySaleLog","部门");
			/// <summary>
			/// 销售员
			/// </summary>
			public readonly static Field SaleName = new Field("SaleName","Finance_EveryDaySaleLog","销售员");
			/// <summary>
			/// 客户/店铺
			/// </summary>
			public readonly static Field Customer = new Field("Customer","Finance_EveryDaySaleLog","客户/店铺");
			/// <summary>
			/// 合同号
			/// </summary>
			public readonly static Field ContractNumber = new Field("ContractNumber","Finance_EveryDaySaleLog","合同号");
			/// <summary>
			/// 产品名称
			/// </summary>
			public readonly static Field ProductName = new Field("ProductName","Finance_EveryDaySaleLog","产品名称");
			/// <summary>
			/// 产品SKU
			/// </summary>
			public readonly static Field ProductSKU = new Field("ProductSKU","Finance_EveryDaySaleLog","产品SKU");
			/// <summary>
			/// 销售数量
			/// </summary>
			public readonly static Field SaleCount = new Field("SaleCount","Finance_EveryDaySaleLog","销售数量");
			/// <summary>
			/// 销售单价
			/// </summary>
			public readonly static Field SalePrice = new Field("SalePrice","Finance_EveryDaySaleLog","销售单价");
			/// <summary>
			/// 货币种类
			/// </summary>
			public readonly static Field Currency = new Field("Currency","Finance_EveryDaySaleLog","货币种类");
			/// <summary>
			/// 汇率
			/// </summary>
			public readonly static Field ExchangeRate = new Field("ExchangeRate","Finance_EveryDaySaleLog","汇率");
			/// <summary>
			/// 销售收入
			/// </summary>
			public readonly static Field SaleIncome = new Field("SaleIncome","Finance_EveryDaySaleLog","销售收入");
			/// <summary>
			/// 材料单价
			/// </summary>
			public readonly static Field MaterialUnitPrice = new Field("MaterialUnitPrice","Finance_EveryDaySaleLog","材料单价");
			/// <summary>
			/// 加工费单价
			/// </summary>
			public readonly static Field ProcessUnitPrice = new Field("ProcessUnitPrice","Finance_EveryDaySaleLog","加工费单价");
			/// <summary>
			/// 材料总价
			/// </summary>
			public readonly static Field MaterialTotalPrice = new Field("MaterialTotalPrice","Finance_EveryDaySaleLog","材料总价");
			/// <summary>
			/// 加工费总价
			/// </summary>
			public readonly static Field ProcessTotalPrice = new Field("ProcessTotalPrice","Finance_EveryDaySaleLog","加工费总价");
			/// <summary>
			/// 毛利额
			/// </summary>
			public readonly static Field GrossProfit = new Field("GrossProfit","Finance_EveryDaySaleLog","毛利额");
			/// <summary>
			/// 毛利率
			/// </summary>
			public readonly static Field GrossProfitRate = new Field("GrossProfitRate","Finance_EveryDaySaleLog","毛利率");
			/// <summary>
			/// 变动费用量
			/// </summary>
			public readonly static Field ChangeCostNumber = new Field("ChangeCostNumber","Finance_EveryDaySaleLog","变动费用量");
			/// <summary>
			/// 变动费用事
			/// </summary>
			public readonly static Field ChangeCostMatter = new Field("ChangeCostMatter","Finance_EveryDaySaleLog","变动费用事");
			/// <summary>
			/// 经营贡献金额
			/// </summary>
			public readonly static Field ContributionMoney = new Field("ContributionMoney","Finance_EveryDaySaleLog","经营贡献金额");
			/// <summary>
			/// 贡献比例
			/// </summary>
			public readonly static Field ContributionRatio = new Field("ContributionRatio","Finance_EveryDaySaleLog","贡献比例");
			/// <summary>
			/// 应收账款平均资金成本_未到期
			/// </summary>
			public readonly static Field AvgCoatUndue = new Field("AvgCoatUndue","Finance_EveryDaySaleLog","应收账款平均资金成本_未到期");
			/// <summary>
			/// 应收账款平均资金成本_当期
			/// </summary>
			public readonly static Field AvgCoatCurrentdue = new Field("AvgCoatCurrentdue","Finance_EveryDaySaleLog","应收账款平均资金成本_当期");
			/// <summary>
			/// 应收账款平均资金成本_逾期
			/// </summary>
			public readonly static Field AvgCoatOverdue = new Field("AvgCoatOverdue","Finance_EveryDaySaleLog","应收账款平均资金成本_逾期");
			/// <summary>
			/// 客户净贡献_金额
			/// </summary>
			public readonly static Field CustomerContributionMoney = new Field("CustomerContributionMoney","Finance_EveryDaySaleLog","客户净贡献_金额");
			/// <summary>
			/// 客户净贡献_比例
			/// </summary>
			public readonly static Field CustomerContributionRatio = new Field("CustomerContributionRatio","Finance_EveryDaySaleLog","客户净贡献_比例");
			/// <summary>
			/// 是否关注
			/// </summary>
			public readonly static Field Follow = new Field("Follow","Finance_EveryDaySaleLog","是否关注");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AddDate = new Field("AddDate","Finance_EveryDaySaleLog","AddDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AddUserId = new Field("AddUserId","Finance_EveryDaySaleLog","AddUserId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastDate = new Field("LastDate","Finance_EveryDaySaleLog","LastDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastUserId = new Field("LastUserId","Finance_EveryDaySaleLog","LastUserId");
			/// <summary>
			/// _1：显示，2：隐藏
			/// </summary>
			public readonly static Field Display = new Field("Display","Finance_EveryDaySaleLog","_1：显示，2：隐藏");
			/// <summary>
			/// 产品规格
			/// </summary>
			public readonly static Field ProductSpecification = new Field("ProductSpecification","Finance_EveryDaySaleLog","产品规格");
			/// <summary>
			/// 供应商
			/// </summary>
			public readonly static Field Supplier = new Field("Supplier","Finance_EveryDaySaleLog","供应商");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SPU = new Field("SPU","Finance_EveryDaySaleLog","SPU");
		}
		#endregion


	}
}

