//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace FancyFix.OA.Model
{

	/// <summary>
	/// 实体类Finance_Statistics 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Finance_Statistics")]
	[Serializable]
	public partial class Finance_Statistics : Entity 
	{
		#region Model
		private int _Id;
		private DateTime? _SaleDate;
		private int? _Year;
		private int? _Month;
		private int? _Day;
		private decimal? _BusinessIncome;
		private decimal? _BudgetaryValue;
		private decimal? _BusinessIncomeRate;
		private decimal? _ActualReceipts;
		private decimal? _ActualDeliveryOrderNumber;
		private decimal? _PlanDeliveryOrderNumber;
		private decimal? _DeliveryPunctualityRate;
		private int? _AddUserId;
		private DateTime? _AddDate;
		private int? _LastUserId;
		private DateTime? _LastDate;
		private int? _Display;
		private string _DepartmentName;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? SaleDate
		{
			get{ return _SaleDate; }
			set
			{
				this.OnPropertyValueChange(_.SaleDate,_SaleDate,value);
				this._SaleDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Year
		{
			get{ return _Year; }
			set
			{
				this.OnPropertyValueChange(_.Year,_Year,value);
				this._Year=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Month
		{
			get{ return _Month; }
			set
			{
				this.OnPropertyValueChange(_.Month,_Month,value);
				this._Month=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Day
		{
			get{ return _Day; }
			set
			{
				this.OnPropertyValueChange(_.Day,_Day,value);
				this._Day=value;
			}
		}
		/// <summary>
		/// 营业收入
		/// </summary>
		public decimal? BusinessIncome
		{
			get{ return _BusinessIncome; }
			set
			{
				this.OnPropertyValueChange(_.BusinessIncome,_BusinessIncome,value);
				this._BusinessIncome=value;
			}
		}
		/// <summary>
		/// 营业收入预算值
		/// </summary>
		public decimal? BudgetaryValue
		{
			get{ return _BudgetaryValue; }
			set
			{
				this.OnPropertyValueChange(_.BudgetaryValue,_BudgetaryValue,value);
				this._BudgetaryValue=value;
			}
		}
		/// <summary>
		/// 营业收入达成率
		/// </summary>
		public decimal? BusinessIncomeRate
		{
			get{ return _BusinessIncomeRate; }
			set
			{
				this.OnPropertyValueChange(_.BusinessIncomeRate,_BusinessIncomeRate,value);
				this._BusinessIncomeRate=value;
			}
		}
		/// <summary>
		/// 实际收款
		/// </summary>
		public decimal? ActualReceipts
		{
			get{ return _ActualReceipts; }
			set
			{
				this.OnPropertyValueChange(_.ActualReceipts,_ActualReceipts,value);
				this._ActualReceipts=value;
			}
		}
		/// <summary>
		/// 实际发货订单数量
		/// </summary>
		public decimal? ActualDeliveryOrderNumber
		{
			get{ return _ActualDeliveryOrderNumber; }
			set
			{
				this.OnPropertyValueChange(_.ActualDeliveryOrderNumber,_ActualDeliveryOrderNumber,value);
				this._ActualDeliveryOrderNumber=value;
			}
		}
		/// <summary>
		/// 计划发货订单数量
		/// </summary>
		public decimal? PlanDeliveryOrderNumber
		{
			get{ return _PlanDeliveryOrderNumber; }
			set
			{
				this.OnPropertyValueChange(_.PlanDeliveryOrderNumber,_PlanDeliveryOrderNumber,value);
				this._PlanDeliveryOrderNumber=value;
			}
		}
		/// <summary>
		/// 发货准时率
		/// </summary>
		public decimal? DeliveryPunctualityRate
		{
			get{ return _DeliveryPunctualityRate; }
			set
			{
				this.OnPropertyValueChange(_.DeliveryPunctualityRate,_DeliveryPunctualityRate,value);
				this._DeliveryPunctualityRate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? AddUserId
		{
			get{ return _AddUserId; }
			set
			{
				this.OnPropertyValueChange(_.AddUserId,_AddUserId,value);
				this._AddUserId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? AddDate
		{
			get{ return _AddDate; }
			set
			{
				this.OnPropertyValueChange(_.AddDate,_AddDate,value);
				this._AddDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? LastUserId
		{
			get{ return _LastUserId; }
			set
			{
				this.OnPropertyValueChange(_.LastUserId,_LastUserId,value);
				this._LastUserId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? LastDate
		{
			get{ return _LastDate; }
			set
			{
				this.OnPropertyValueChange(_.LastDate,_LastDate,value);
				this._LastDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Display
		{
			get{ return _Display; }
			set
			{
				this.OnPropertyValueChange(_.Display,_Display,value);
				this._Display=value;
			}
		}
		/// <summary>
		/// 部门
		/// </summary>
		public string DepartmentName
		{
			get{ return _DepartmentName; }
			set
			{
				this.OnPropertyValueChange(_.DepartmentName,_DepartmentName,value);
				this._DepartmentName=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.SaleDate,
				_.Year,
				_.Month,
				_.Day,
				_.BusinessIncome,
				_.BudgetaryValue,
				_.BusinessIncomeRate,
				_.ActualReceipts,
				_.ActualDeliveryOrderNumber,
				_.PlanDeliveryOrderNumber,
				_.DeliveryPunctualityRate,
				_.AddUserId,
				_.AddDate,
				_.LastUserId,
				_.LastDate,
				_.Display,
				_.DepartmentName};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._SaleDate,
				this._Year,
				this._Month,
				this._Day,
				this._BusinessIncome,
				this._BudgetaryValue,
				this._BusinessIncomeRate,
				this._ActualReceipts,
				this._ActualDeliveryOrderNumber,
				this._PlanDeliveryOrderNumber,
				this._DeliveryPunctualityRate,
				this._AddUserId,
				this._AddDate,
				this._LastUserId,
				this._LastDate,
				this._Display,
				this._DepartmentName};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Finance_Statistics");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Finance_Statistics","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SaleDate = new Field("SaleDate","Finance_Statistics","SaleDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Year = new Field("Year","Finance_Statistics","Year");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Month = new Field("Month","Finance_Statistics","Month");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Day = new Field("Day","Finance_Statistics","Day");
			/// <summary>
			/// 营业收入
			/// </summary>
			public readonly static Field BusinessIncome = new Field("BusinessIncome","Finance_Statistics","营业收入");
			/// <summary>
			/// 营业收入预算值
			/// </summary>
			public readonly static Field BudgetaryValue = new Field("BudgetaryValue","Finance_Statistics","营业收入预算值");
			/// <summary>
			/// 营业收入达成率
			/// </summary>
			public readonly static Field BusinessIncomeRate = new Field("BusinessIncomeRate","Finance_Statistics","营业收入达成率");
			/// <summary>
			/// 实际收款
			/// </summary>
			public readonly static Field ActualReceipts = new Field("ActualReceipts","Finance_Statistics","实际收款");
			/// <summary>
			/// 实际发货订单数量
			/// </summary>
			public readonly static Field ActualDeliveryOrderNumber = new Field("ActualDeliveryOrderNumber","Finance_Statistics","实际发货订单数量");
			/// <summary>
			/// 计划发货订单数量
			/// </summary>
			public readonly static Field PlanDeliveryOrderNumber = new Field("PlanDeliveryOrderNumber","Finance_Statistics","计划发货订单数量");
			/// <summary>
			/// 发货准时率
			/// </summary>
			public readonly static Field DeliveryPunctualityRate = new Field("DeliveryPunctualityRate","Finance_Statistics","发货准时率");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AddUserId = new Field("AddUserId","Finance_Statistics","AddUserId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AddDate = new Field("AddDate","Finance_Statistics","AddDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastUserId = new Field("LastUserId","Finance_Statistics","LastUserId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastDate = new Field("LastDate","Finance_Statistics","LastDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Display = new Field("Display","Finance_Statistics","Display");
			/// <summary>
			/// 部门
			/// </summary>
			public readonly static Field DepartmentName = new Field("DepartmentName","Finance_Statistics","部门");
		}
		#endregion


	}
}

