//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace FancyFix.OA.Model
{

	/// <summary>
	/// 实体类Kpi_Records 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Kpi_Records")]
	[Serializable]
	public partial class Kpi_Records : Entity 
	{
		#region Model
		private int _Id;
		private string _Name;
		private string _Content;
		private string _Target_Normal;
		private string _Target_Highest;
		private string _Target_Lowest;
		private int? _Score;
		private int? _UserId;
		private string _UserName;
		private int? _ParUserId;
		private string _ParUserName;
		private int? _Year;
		private int? _Month;
		private DateTime? _CreateTime;
		private bool? _IsApprove;
		private int? _Pid;
		private string _Remark;
		private DateTime? _ApproveTime;
		private bool? _IsCreated;
		private string _TargetRemark;
		private int? _ParScore;
		private decimal? _FinishScore;
		private int? _SelfScore;
		private string _SelfRemark;
		private DateTime? _SelfApproveTime;
		private bool? _IsSelfApprove;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Content
		{
			get{ return _Content; }
			set
			{
				this.OnPropertyValueChange(_.Content,_Content,value);
				this._Content=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Target_Normal
		{
			get{ return _Target_Normal; }
			set
			{
				this.OnPropertyValueChange(_.Target_Normal,_Target_Normal,value);
				this._Target_Normal=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Target_Highest
		{
			get{ return _Target_Highest; }
			set
			{
				this.OnPropertyValueChange(_.Target_Highest,_Target_Highest,value);
				this._Target_Highest=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Target_Lowest
		{
			get{ return _Target_Lowest; }
			set
			{
				this.OnPropertyValueChange(_.Target_Lowest,_Target_Lowest,value);
				this._Target_Lowest=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Score
		{
			get{ return _Score; }
			set
			{
				this.OnPropertyValueChange(_.Score,_Score,value);
				this._Score=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? UserId
		{
			get{ return _UserId; }
			set
			{
				this.OnPropertyValueChange(_.UserId,_UserId,value);
				this._UserId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string UserName
		{
			get{ return _UserName; }
			set
			{
				this.OnPropertyValueChange(_.UserName,_UserName,value);
				this._UserName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ParUserId
		{
			get{ return _ParUserId; }
			set
			{
				this.OnPropertyValueChange(_.ParUserId,_ParUserId,value);
				this._ParUserId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ParUserName
		{
			get{ return _ParUserName; }
			set
			{
				this.OnPropertyValueChange(_.ParUserName,_ParUserName,value);
				this._ParUserName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Year
		{
			get{ return _Year; }
			set
			{
				this.OnPropertyValueChange(_.Year,_Year,value);
				this._Year=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Month
		{
			get{ return _Month; }
			set
			{
				this.OnPropertyValueChange(_.Month,_Month,value);
				this._Month=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool? IsApprove
		{
			get{ return _IsApprove; }
			set
			{
				this.OnPropertyValueChange(_.IsApprove,_IsApprove,value);
				this._IsApprove=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Pid
		{
			get{ return _Pid; }
			set
			{
				this.OnPropertyValueChange(_.Pid,_Pid,value);
				this._Pid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange(_.Remark,_Remark,value);
				this._Remark=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? ApproveTime
		{
			get{ return _ApproveTime; }
			set
			{
				this.OnPropertyValueChange(_.ApproveTime,_ApproveTime,value);
				this._ApproveTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool? IsCreated
		{
			get{ return _IsCreated; }
			set
			{
				this.OnPropertyValueChange(_.IsCreated,_IsCreated,value);
				this._IsCreated=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TargetRemark
		{
			get{ return _TargetRemark; }
			set
			{
				this.OnPropertyValueChange(_.TargetRemark,_TargetRemark,value);
				this._TargetRemark=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ParScore
		{
			get{ return _ParScore; }
			set
			{
				this.OnPropertyValueChange(_.ParScore,_ParScore,value);
				this._ParScore=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? FinishScore
		{
			get{ return _FinishScore; }
			set
			{
				this.OnPropertyValueChange(_.FinishScore,_FinishScore,value);
				this._FinishScore=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? SelfScore
		{
			get{ return _SelfScore; }
			set
			{
				this.OnPropertyValueChange(_.SelfScore,_SelfScore,value);
				this._SelfScore=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SelfRemark
		{
			get{ return _SelfRemark; }
			set
			{
				this.OnPropertyValueChange(_.SelfRemark,_SelfRemark,value);
				this._SelfRemark=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? SelfApproveTime
		{
			get{ return _SelfApproveTime; }
			set
			{
				this.OnPropertyValueChange(_.SelfApproveTime,_SelfApproveTime,value);
				this._SelfApproveTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool? IsSelfApprove
		{
			get{ return _IsSelfApprove; }
			set
			{
				this.OnPropertyValueChange(_.IsSelfApprove,_IsSelfApprove,value);
				this._IsSelfApprove=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Name,
				_.Content,
				_.Target_Normal,
				_.Target_Highest,
				_.Target_Lowest,
				_.Score,
				_.UserId,
				_.UserName,
				_.ParUserId,
				_.ParUserName,
				_.Year,
				_.Month,
				_.CreateTime,
				_.IsApprove,
				_.Pid,
				_.Remark,
				_.ApproveTime,
				_.IsCreated,
				_.TargetRemark,
				_.ParScore,
				_.FinishScore,
				_.SelfScore,
				_.SelfRemark,
				_.SelfApproveTime,
				_.IsSelfApprove};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Name,
				this._Content,
				this._Target_Normal,
				this._Target_Highest,
				this._Target_Lowest,
				this._Score,
				this._UserId,
				this._UserName,
				this._ParUserId,
				this._ParUserName,
				this._Year,
				this._Month,
				this._CreateTime,
				this._IsApprove,
				this._Pid,
				this._Remark,
				this._ApproveTime,
				this._IsCreated,
				this._TargetRemark,
				this._ParScore,
				this._FinishScore,
				this._SelfScore,
				this._SelfRemark,
				this._SelfApproveTime,
				this._IsSelfApprove};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Kpi_Records");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Kpi_Records","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name","Kpi_Records","Name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Content = new Field("Content","Kpi_Records","Content");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Target_Normal = new Field("Target_Normal","Kpi_Records","Target_Normal");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Target_Highest = new Field("Target_Highest","Kpi_Records","Target_Highest");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Target_Lowest = new Field("Target_Lowest","Kpi_Records","Target_Lowest");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Score = new Field("Score","Kpi_Records","Score");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UserId = new Field("UserId","Kpi_Records","UserId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UserName = new Field("UserName","Kpi_Records","UserName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ParUserId = new Field("ParUserId","Kpi_Records","ParUserId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ParUserName = new Field("ParUserName","Kpi_Records","ParUserName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Year = new Field("Year","Kpi_Records","Year");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Month = new Field("Month","Kpi_Records","Month");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","Kpi_Records","CreateTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsApprove = new Field("IsApprove","Kpi_Records","IsApprove");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Pid = new Field("Pid","Kpi_Records","Pid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Remark = new Field("Remark","Kpi_Records","Remark");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ApproveTime = new Field("ApproveTime","Kpi_Records","ApproveTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsCreated = new Field("IsCreated","Kpi_Records","IsCreated");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TargetRemark = new Field("TargetRemark","Kpi_Records","TargetRemark");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ParScore = new Field("ParScore","Kpi_Records","ParScore");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FinishScore = new Field("FinishScore","Kpi_Records","FinishScore");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SelfScore = new Field("SelfScore","Kpi_Records","SelfScore");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SelfRemark = new Field("SelfRemark","Kpi_Records","SelfRemark");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SelfApproveTime = new Field("SelfApproveTime","Kpi_Records","SelfApproveTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsSelfApprove = new Field("IsSelfApprove","Kpi_Records","IsSelfApprove");
		}
		#endregion


	}
}

