//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace FancyFix.OA.Model
{

	/// <summary>
	/// 实体类Mng_User 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Mng_User")]
	[Serializable]
	public partial class Mng_User : Entity 
	{
		#region Model
		private int _Id;
		private string _UserName;
		private string _Password;
		private string _RealName;
		private DateTime? _LoginTime;
		private int? _LoginTimes;
		private string _LoginIp;
		private bool? _Sex;
		private string _Pic;
		private string _Email;
		private string _Tel;
		private string _QQ;
		private bool? _InJob;
		private int? _DepartId;
		private int? _GroupId;
		private int? _ParUserId;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string UserName
		{
			get{ return _UserName; }
			set
			{
				this.OnPropertyValueChange(_.UserName,_UserName,value);
				this._UserName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Password
		{
			get{ return _Password; }
			set
			{
				this.OnPropertyValueChange(_.Password,_Password,value);
				this._Password=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string RealName
		{
			get{ return _RealName; }
			set
			{
				this.OnPropertyValueChange(_.RealName,_RealName,value);
				this._RealName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? LoginTime
		{
			get{ return _LoginTime; }
			set
			{
				this.OnPropertyValueChange(_.LoginTime,_LoginTime,value);
				this._LoginTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? LoginTimes
		{
			get{ return _LoginTimes; }
			set
			{
				this.OnPropertyValueChange(_.LoginTimes,_LoginTimes,value);
				this._LoginTimes=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string LoginIp
		{
			get{ return _LoginIp; }
			set
			{
				this.OnPropertyValueChange(_.LoginIp,_LoginIp,value);
				this._LoginIp=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool? Sex
		{
			get{ return _Sex; }
			set
			{
				this.OnPropertyValueChange(_.Sex,_Sex,value);
				this._Sex=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Pic
		{
			get{ return _Pic; }
			set
			{
				this.OnPropertyValueChange(_.Pic,_Pic,value);
				this._Pic=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Email
		{
			get{ return _Email; }
			set
			{
				this.OnPropertyValueChange(_.Email,_Email,value);
				this._Email=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Tel
		{
			get{ return _Tel; }
			set
			{
				this.OnPropertyValueChange(_.Tel,_Tel,value);
				this._Tel=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string QQ
		{
			get{ return _QQ; }
			set
			{
				this.OnPropertyValueChange(_.QQ,_QQ,value);
				this._QQ=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool? InJob
		{
			get{ return _InJob; }
			set
			{
				this.OnPropertyValueChange(_.InJob,_InJob,value);
				this._InJob=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? DepartId
		{
			get{ return _DepartId; }
			set
			{
				this.OnPropertyValueChange(_.DepartId,_DepartId,value);
				this._DepartId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? GroupId
		{
			get{ return _GroupId; }
			set
			{
				this.OnPropertyValueChange(_.GroupId,_GroupId,value);
				this._GroupId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ParUserId
		{
			get{ return _ParUserId; }
			set
			{
				this.OnPropertyValueChange(_.ParUserId,_ParUserId,value);
				this._ParUserId=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.UserName,
				_.Password,
				_.RealName,
				_.LoginTime,
				_.LoginTimes,
				_.LoginIp,
				_.Sex,
				_.Pic,
				_.Email,
				_.Tel,
				_.QQ,
				_.InJob,
				_.DepartId,
				_.GroupId,
				_.ParUserId};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._UserName,
				this._Password,
				this._RealName,
				this._LoginTime,
				this._LoginTimes,
				this._LoginIp,
				this._Sex,
				this._Pic,
				this._Email,
				this._Tel,
				this._QQ,
				this._InJob,
				this._DepartId,
				this._GroupId,
				this._ParUserId};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Mng_User");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Mng_User","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UserName = new Field("UserName","Mng_User","UserName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Password = new Field("Password","Mng_User","Password");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RealName = new Field("RealName","Mng_User","RealName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LoginTime = new Field("LoginTime","Mng_User","LoginTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LoginTimes = new Field("LoginTimes","Mng_User","LoginTimes");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LoginIp = new Field("LoginIp","Mng_User","LoginIp");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Sex = new Field("Sex","Mng_User","Sex");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Pic = new Field("Pic","Mng_User","Pic");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Email = new Field("Email","Mng_User","Email");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Tel = new Field("Tel","Mng_User","Tel");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field QQ = new Field("QQ","Mng_User","QQ");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field InJob = new Field("InJob","Mng_User","InJob");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DepartId = new Field("DepartId","Mng_User","DepartId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GroupId = new Field("GroupId","Mng_User","GroupId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ParUserId = new Field("ParUserId","Mng_User","ParUserId");
		}
		#endregion


	}
}

