//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace FancyFix.OA.Model
{

	/// <summary>
	/// 实体类Mng_PermissionGroup 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Mng_PermissionGroup")]
	[Serializable]
	public partial class Mng_PermissionGroup : Entity 
	{
		#region Model
		private int _Id;
		private string _GroupName;
		private string _Title;
		private DateTime? _LastEditTime;
		private int? _LastEditor;
		private bool? _BeLock;
		private int? _Sequence;
		private int? _DepartId;
		private bool? _IsAdmin;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string GroupName
		{
			get{ return _GroupName; }
			set
			{
				this.OnPropertyValueChange(_.GroupName,_GroupName,value);
				this._GroupName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Title
		{
			get{ return _Title; }
			set
			{
				this.OnPropertyValueChange(_.Title,_Title,value);
				this._Title=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? LastEditTime
		{
			get{ return _LastEditTime; }
			set
			{
				this.OnPropertyValueChange(_.LastEditTime,_LastEditTime,value);
				this._LastEditTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? LastEditor
		{
			get{ return _LastEditor; }
			set
			{
				this.OnPropertyValueChange(_.LastEditor,_LastEditor,value);
				this._LastEditor=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool? BeLock
		{
			get{ return _BeLock; }
			set
			{
				this.OnPropertyValueChange(_.BeLock,_BeLock,value);
				this._BeLock=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Sequence
		{
			get{ return _Sequence; }
			set
			{
				this.OnPropertyValueChange(_.Sequence,_Sequence,value);
				this._Sequence=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? DepartId
		{
			get{ return _DepartId; }
			set
			{
				this.OnPropertyValueChange(_.DepartId,_DepartId,value);
				this._DepartId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool? IsAdmin
		{
			get{ return _IsAdmin; }
			set
			{
				this.OnPropertyValueChange(_.IsAdmin,_IsAdmin,value);
				this._IsAdmin=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.GroupName,
				_.Title,
				_.LastEditTime,
				_.LastEditor,
				_.BeLock,
				_.Sequence,
				_.DepartId,
				_.IsAdmin};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._GroupName,
				this._Title,
				this._LastEditTime,
				this._LastEditor,
				this._BeLock,
				this._Sequence,
				this._DepartId,
				this._IsAdmin};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Mng_PermissionGroup");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Mng_PermissionGroup","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GroupName = new Field("GroupName","Mng_PermissionGroup","GroupName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Title = new Field("Title","Mng_PermissionGroup","Title");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastEditTime = new Field("LastEditTime","Mng_PermissionGroup","LastEditTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastEditor = new Field("LastEditor","Mng_PermissionGroup","LastEditor");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BeLock = new Field("BeLock","Mng_PermissionGroup","BeLock");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Sequence = new Field("Sequence","Mng_PermissionGroup","Sequence");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DepartId = new Field("DepartId","Mng_PermissionGroup","DepartId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsAdmin = new Field("IsAdmin","Mng_PermissionGroup","IsAdmin");
		}
		#endregion


	}
}

