//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace FancyFix.OA.Model
{

	/// <summary>
	/// 实体类Order_Contract 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Order_Contract")]
	[Serializable]
	public partial class Order_Contract : Entity 
	{
		#region Model
		private int _Id;
		private string _ContractNo;
		private DateTime? _AddTime;
		private int? _AdminId;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 合同号
		/// </summary>
		public string ContractNo
		{
			get{ return _ContractNo; }
			set
			{
				this.OnPropertyValueChange(_.ContractNo,_ContractNo,value);
				this._ContractNo=value;
			}
		}
		/// <summary>
		/// 记录添加时间
		/// </summary>
		public DateTime? AddTime
		{
			get{ return _AddTime; }
			set
			{
				this.OnPropertyValueChange(_.AddTime,_AddTime,value);
				this._AddTime=value;
			}
		}
		/// <summary>
		/// 添加人
		/// </summary>
		public int? AdminId
		{
			get{ return _AdminId; }
			set
			{
				this.OnPropertyValueChange(_.AdminId,_AdminId,value);
				this._AdminId=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.ContractNo,
				_.AddTime,
				_.AdminId};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._ContractNo,
				this._AddTime,
				this._AdminId};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Order_Contract");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Order_Contract","Id");
			/// <summary>
			/// 合同号
			/// </summary>
			public readonly static Field ContractNo = new Field("ContractNo","Order_Contract","合同号");
			/// <summary>
			/// 记录添加时间
			/// </summary>
			public readonly static Field AddTime = new Field("AddTime","Order_Contract","记录添加时间");
			/// <summary>
			/// 添加人
			/// </summary>
			public readonly static Field AdminId = new Field("AdminId","Order_Contract","添加人");
		}
		#endregion


	}
}

