//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace FancyFix.OA.Model
{

	/// <summary>
	/// 实体类Order_ContractProduct 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Order_ContractProduct")]
	[Serializable]
	public partial class Order_ContractProduct : Entity 
	{
		#region Model
		private int _Id;
		private int? _ContractId;
		private string _Name;
		private int? _Quantity;
		private decimal? _Price;
		private decimal? _TotalPrice;
		private DateTime? _AddTime;
		private int? _AdminId;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ContractId
		{
			get{ return _ContractId; }
			set
			{
				this.OnPropertyValueChange(_.ContractId,_ContractId,value);
				this._ContractId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Quantity
		{
			get{ return _Quantity; }
			set
			{
				this.OnPropertyValueChange(_.Quantity,_Quantity,value);
				this._Quantity=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? Price
		{
			get{ return _Price; }
			set
			{
				this.OnPropertyValueChange(_.Price,_Price,value);
				this._Price=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? TotalPrice
		{
			get{ return _TotalPrice; }
			set
			{
				this.OnPropertyValueChange(_.TotalPrice,_TotalPrice,value);
				this._TotalPrice=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? AddTime
		{
			get{ return _AddTime; }
			set
			{
				this.OnPropertyValueChange(_.AddTime,_AddTime,value);
				this._AddTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? AdminId
		{
			get{ return _AdminId; }
			set
			{
				this.OnPropertyValueChange(_.AdminId,_AdminId,value);
				this._AdminId=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.ContractId,
				_.Name,
				_.Quantity,
				_.Price,
				_.TotalPrice,
				_.AddTime,
				_.AdminId};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._ContractId,
				this._Name,
				this._Quantity,
				this._Price,
				this._TotalPrice,
				this._AddTime,
				this._AdminId};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Order_ContractProduct");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Order_ContractProduct","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ContractId = new Field("ContractId","Order_ContractProduct","ContractId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name","Order_ContractProduct","Name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Quantity = new Field("Quantity","Order_ContractProduct","Quantity");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Price = new Field("Price","Order_ContractProduct","Price");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TotalPrice = new Field("TotalPrice","Order_ContractProduct","TotalPrice");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AddTime = new Field("AddTime","Order_ContractProduct","AddTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AdminId = new Field("AdminId","Order_ContractProduct","AdminId");
		}
		#endregion


	}
}

