//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace FancyFix.OA.Model
{

	/// <summary>
	/// 实体类Point_Records 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Point_Records")]
	[Serializable]
	public partial class Point_Records : Entity 
	{
		#region Model
		private int _Id;
		private int? _PointId;
		private string _Content;
		private int? _UserId;
		private string _UserName;
		private int? _Score;
		private int? _ParUserId;
		private string _ParUserName;
		private DateTime? _CreateTime;
		private DateTime? _UpdateTime;
		private DateTime? _ApproveTime;
		private string _Remark;
		private bool? _IsApprove;
		private DateTime? _EventTime;
		private int? _Year;
		private int? _Month;
		private bool? _IsPass;
		private int? _CreateUserId;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? PointId
		{
			get{ return _PointId; }
			set
			{
				this.OnPropertyValueChange(_.PointId,_PointId,value);
				this._PointId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Content
		{
			get{ return _Content; }
			set
			{
				this.OnPropertyValueChange(_.Content,_Content,value);
				this._Content=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? UserId
		{
			get{ return _UserId; }
			set
			{
				this.OnPropertyValueChange(_.UserId,_UserId,value);
				this._UserId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string UserName
		{
			get{ return _UserName; }
			set
			{
				this.OnPropertyValueChange(_.UserName,_UserName,value);
				this._UserName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Score
		{
			get{ return _Score; }
			set
			{
				this.OnPropertyValueChange(_.Score,_Score,value);
				this._Score=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ParUserId
		{
			get{ return _ParUserId; }
			set
			{
				this.OnPropertyValueChange(_.ParUserId,_ParUserId,value);
				this._ParUserId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ParUserName
		{
			get{ return _ParUserName; }
			set
			{
				this.OnPropertyValueChange(_.ParUserName,_ParUserName,value);
				this._ParUserName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdateTime
		{
			get{ return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange(_.UpdateTime,_UpdateTime,value);
				this._UpdateTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? ApproveTime
		{
			get{ return _ApproveTime; }
			set
			{
				this.OnPropertyValueChange(_.ApproveTime,_ApproveTime,value);
				this._ApproveTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange(_.Remark,_Remark,value);
				this._Remark=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool? IsApprove
		{
			get{ return _IsApprove; }
			set
			{
				this.OnPropertyValueChange(_.IsApprove,_IsApprove,value);
				this._IsApprove=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? EventTime
		{
			get{ return _EventTime; }
			set
			{
				this.OnPropertyValueChange(_.EventTime,_EventTime,value);
				this._EventTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Year
		{
			get{ return _Year; }
			set
			{
				this.OnPropertyValueChange(_.Year,_Year,value);
				this._Year=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Month
		{
			get{ return _Month; }
			set
			{
				this.OnPropertyValueChange(_.Month,_Month,value);
				this._Month=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool? IsPass
		{
			get{ return _IsPass; }
			set
			{
				this.OnPropertyValueChange(_.IsPass,_IsPass,value);
				this._IsPass=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CreateUserId
		{
			get{ return _CreateUserId; }
			set
			{
				this.OnPropertyValueChange(_.CreateUserId,_CreateUserId,value);
				this._CreateUserId=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.PointId,
				_.Content,
				_.UserId,
				_.UserName,
				_.Score,
				_.ParUserId,
				_.ParUserName,
				_.CreateTime,
				_.UpdateTime,
				_.ApproveTime,
				_.Remark,
				_.IsApprove,
				_.EventTime,
				_.Year,
				_.Month,
				_.IsPass,
				_.CreateUserId};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._PointId,
				this._Content,
				this._UserId,
				this._UserName,
				this._Score,
				this._ParUserId,
				this._ParUserName,
				this._CreateTime,
				this._UpdateTime,
				this._ApproveTime,
				this._Remark,
				this._IsApprove,
				this._EventTime,
				this._Year,
				this._Month,
				this._IsPass,
				this._CreateUserId};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Point_Records");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Point_Records","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PointId = new Field("PointId","Point_Records","PointId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Content = new Field("Content","Point_Records","Content");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UserId = new Field("UserId","Point_Records","UserId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UserName = new Field("UserName","Point_Records","UserName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Score = new Field("Score","Point_Records","Score");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ParUserId = new Field("ParUserId","Point_Records","ParUserId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ParUserName = new Field("ParUserName","Point_Records","ParUserName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","Point_Records","CreateTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime","Point_Records","UpdateTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ApproveTime = new Field("ApproveTime","Point_Records","ApproveTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Remark = new Field("Remark","Point_Records","Remark");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsApprove = new Field("IsApprove","Point_Records","IsApprove");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EventTime = new Field("EventTime","Point_Records","EventTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Year = new Field("Year","Point_Records","Year");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Month = new Field("Month","Point_Records","Month");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsPass = new Field("IsPass","Point_Records","IsPass");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateUserId = new Field("CreateUserId","Point_Records","CreateUserId");
		}
		#endregion


	}
}

