//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace FancyFix.OA.Model
{

	/// <summary>
	/// 实体类Point_List 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Point_List")]
	[Serializable]
	public partial class Point_List : Entity 
	{
		#region Model
		private int _Id;
		private int? _ClassId;
		private string _ClassName;
		private string _PointName;
		private int? _PointScore;
		private DateTime? _CreateTime;
		private int? _Sequence;
		private string _CountTime;
		private bool? _CountBySelf;
		private bool? _BeLock;
		private string _Remark;
		private string _ScoreRemark;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ClassId
		{
			get{ return _ClassId; }
			set
			{
				this.OnPropertyValueChange(_.ClassId,_ClassId,value);
				this._ClassId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ClassName
		{
			get{ return _ClassName; }
			set
			{
				this.OnPropertyValueChange(_.ClassName,_ClassName,value);
				this._ClassName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PointName
		{
			get{ return _PointName; }
			set
			{
				this.OnPropertyValueChange(_.PointName,_PointName,value);
				this._PointName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? PointScore
		{
			get{ return _PointScore; }
			set
			{
				this.OnPropertyValueChange(_.PointScore,_PointScore,value);
				this._PointScore=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Sequence
		{
			get{ return _Sequence; }
			set
			{
				this.OnPropertyValueChange(_.Sequence,_Sequence,value);
				this._Sequence=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CountTime
		{
			get{ return _CountTime; }
			set
			{
				this.OnPropertyValueChange(_.CountTime,_CountTime,value);
				this._CountTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool? CountBySelf
		{
			get{ return _CountBySelf; }
			set
			{
				this.OnPropertyValueChange(_.CountBySelf,_CountBySelf,value);
				this._CountBySelf=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool? BeLock
		{
			get{ return _BeLock; }
			set
			{
				this.OnPropertyValueChange(_.BeLock,_BeLock,value);
				this._BeLock=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange(_.Remark,_Remark,value);
				this._Remark=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ScoreRemark
		{
			get{ return _ScoreRemark; }
			set
			{
				this.OnPropertyValueChange(_.ScoreRemark,_ScoreRemark,value);
				this._ScoreRemark=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.ClassId,
				_.ClassName,
				_.PointName,
				_.PointScore,
				_.CreateTime,
				_.Sequence,
				_.CountTime,
				_.CountBySelf,
				_.BeLock,
				_.Remark,
				_.ScoreRemark};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._ClassId,
				this._ClassName,
				this._PointName,
				this._PointScore,
				this._CreateTime,
				this._Sequence,
				this._CountTime,
				this._CountBySelf,
				this._BeLock,
				this._Remark,
				this._ScoreRemark};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Point_List");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Point_List","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ClassId = new Field("ClassId","Point_List","ClassId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ClassName = new Field("ClassName","Point_List","ClassName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PointName = new Field("PointName","Point_List","PointName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PointScore = new Field("PointScore","Point_List","PointScore");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","Point_List","CreateTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Sequence = new Field("Sequence","Point_List","Sequence");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CountTime = new Field("CountTime","Point_List","CountTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CountBySelf = new Field("CountBySelf","Point_List","CountBySelf");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BeLock = new Field("BeLock","Point_List","BeLock");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Remark = new Field("Remark","Point_List","Remark");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ScoreRemark = new Field("ScoreRemark","Point_List","ScoreRemark");
		}
		#endregion


	}
}

