//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace FancyFix.OA.Model
{

	/// <summary>
	/// 实体类Product_AttributeSet 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Product_AttributeSet")]
	[Serializable]
	public partial class Product_AttributeSet : Entity 
	{
		#region Model
		private int _Id;
		private int? _ProductId;
		private int? _AttributeId;
		private int? _AttributeValueId;
		private string _AttributeValue;
		private bool? _IsSpu;
		/// <summary>
		/// 自增Id
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 产品Id
		/// </summary>
		public int? ProductId
		{
			get{ return _ProductId; }
			set
			{
				this.OnPropertyValueChange(_.ProductId,_ProductId,value);
				this._ProductId=value;
			}
		}
		/// <summary>
		/// 属性Id
		/// </summary>
		public int? AttributeId
		{
			get{ return _AttributeId; }
			set
			{
				this.OnPropertyValueChange(_.AttributeId,_AttributeId,value);
				this._AttributeId=value;
			}
		}
		/// <summary>
		/// 属性值Id
		/// </summary>
		public int? AttributeValueId
		{
			get{ return _AttributeValueId; }
			set
			{
				this.OnPropertyValueChange(_.AttributeValueId,_AttributeValueId,value);
				this._AttributeValueId=value;
			}
		}
		/// <summary>
		/// 属性值
		/// </summary>
		public string AttributeValue
		{
			get{ return _AttributeValue; }
			set
			{
				this.OnPropertyValueChange(_.AttributeValue,_AttributeValue,value);
				this._AttributeValue=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool? IsSpu
		{
			get{ return _IsSpu; }
			set
			{
				this.OnPropertyValueChange(_.IsSpu,_IsSpu,value);
				this._IsSpu=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.ProductId,
				_.AttributeId,
				_.AttributeValueId,
				_.AttributeValue,
				_.IsSpu};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._ProductId,
				this._AttributeId,
				this._AttributeValueId,
				this._AttributeValue,
				this._IsSpu};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Product_AttributeSet");
			/// <summary>
			/// 自增Id
			/// </summary>
			public readonly static Field Id = new Field("Id","Product_AttributeSet","自增Id");
			/// <summary>
			/// 产品Id
			/// </summary>
			public readonly static Field ProductId = new Field("ProductId","Product_AttributeSet","产品Id");
			/// <summary>
			/// 属性Id
			/// </summary>
			public readonly static Field AttributeId = new Field("AttributeId","Product_AttributeSet","属性Id");
			/// <summary>
			/// 属性值Id
			/// </summary>
			public readonly static Field AttributeValueId = new Field("AttributeValueId","Product_AttributeSet","属性值Id");
			/// <summary>
			/// 属性值
			/// </summary>
			public readonly static Field AttributeValue = new Field("AttributeValue","Product_AttributeSet","属性值");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsSpu = new Field("IsSpu","Product_AttributeSet","IsSpu");
		}
		#endregion


	}
}

