//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace FancyFix.OA.Model
{

	/// <summary>
	/// 实体类Product_Image 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Product_Image")]
	[Serializable]
	public partial class Product_Image : Entity 
	{
		#region Model
		private int _Id;
		private string _ImagePath;
		private string _ImageExt;
		private int _FileSize;
		private int _SmallWidth;
		private int _SmailHeight;
		private int? _MiddleWidth;
		private int? _MiddleHeight;
		private int _BigWidth;
		private int _BigHeight;
		private int? _MinWidth;
		private int? _MinHeight;
		private string _Md5;
		private DateTime? _AddTime;
		private int? _ProId;
		private string _Tag;
		private int? _Type;
		/// <summary>
		/// 自增Id
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 图片路径
		/// </summary>
		public string ImagePath
		{
			get{ return _ImagePath; }
			set
			{
				this.OnPropertyValueChange(_.ImagePath,_ImagePath,value);
				this._ImagePath=value;
			}
		}
		/// <summary>
		/// 图片格式
		/// </summary>
		public string ImageExt
		{
			get{ return _ImageExt; }
			set
			{
				this.OnPropertyValueChange(_.ImageExt,_ImageExt,value);
				this._ImageExt=value;
			}
		}
		/// <summary>
		/// 文件大小
		/// </summary>
		public int FileSize
		{
			get{ return _FileSize; }
			set
			{
				this.OnPropertyValueChange(_.FileSize,_FileSize,value);
				this._FileSize=value;
			}
		}
		/// <summary>
		/// 最小宽度
		/// </summary>
		public int SmallWidth
		{
			get{ return _SmallWidth; }
			set
			{
				this.OnPropertyValueChange(_.SmallWidth,_SmallWidth,value);
				this._SmallWidth=value;
			}
		}
		/// <summary>
		/// 最小高度
		/// </summary>
		public int SmailHeight
		{
			get{ return _SmailHeight; }
			set
			{
				this.OnPropertyValueChange(_.SmailHeight,_SmailHeight,value);
				this._SmailHeight=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? MiddleWidth
		{
			get{ return _MiddleWidth; }
			set
			{
				this.OnPropertyValueChange(_.MiddleWidth,_MiddleWidth,value);
				this._MiddleWidth=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? MiddleHeight
		{
			get{ return _MiddleHeight; }
			set
			{
				this.OnPropertyValueChange(_.MiddleHeight,_MiddleHeight,value);
				this._MiddleHeight=value;
			}
		}
		/// <summary>
		/// 最大宽度
		/// </summary>
		public int BigWidth
		{
			get{ return _BigWidth; }
			set
			{
				this.OnPropertyValueChange(_.BigWidth,_BigWidth,value);
				this._BigWidth=value;
			}
		}
		/// <summary>
		/// 最大高度
		/// </summary>
		public int BigHeight
		{
			get{ return _BigHeight; }
			set
			{
				this.OnPropertyValueChange(_.BigHeight,_BigHeight,value);
				this._BigHeight=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? MinWidth
		{
			get{ return _MinWidth; }
			set
			{
				this.OnPropertyValueChange(_.MinWidth,_MinWidth,value);
				this._MinWidth=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? MinHeight
		{
			get{ return _MinHeight; }
			set
			{
				this.OnPropertyValueChange(_.MinHeight,_MinHeight,value);
				this._MinHeight=value;
			}
		}
		/// <summary>
		/// 文件MD5
		/// </summary>
		public string Md5
		{
			get{ return _Md5; }
			set
			{
				this.OnPropertyValueChange(_.Md5,_Md5,value);
				this._Md5=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? AddTime
		{
			get{ return _AddTime; }
			set
			{
				this.OnPropertyValueChange(_.AddTime,_AddTime,value);
				this._AddTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ProId
		{
			get{ return _ProId; }
			set
			{
				this.OnPropertyValueChange(_.ProId,_ProId,value);
				this._ProId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Tag
		{
			get{ return _Tag; }
			set
			{
				this.OnPropertyValueChange(_.Tag,_Tag,value);
				this._Tag=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Type
		{
			get{ return _Type; }
			set
			{
				this.OnPropertyValueChange(_.Type,_Type,value);
				this._Type=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.ImagePath,
				_.ImageExt,
				_.FileSize,
				_.SmallWidth,
				_.SmailHeight,
				_.MiddleWidth,
				_.MiddleHeight,
				_.BigWidth,
				_.BigHeight,
				_.MinWidth,
				_.MinHeight,
				_.Md5,
				_.AddTime,
				_.ProId,
				_.Tag,
				_.Type};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._ImagePath,
				this._ImageExt,
				this._FileSize,
				this._SmallWidth,
				this._SmailHeight,
				this._MiddleWidth,
				this._MiddleHeight,
				this._BigWidth,
				this._BigHeight,
				this._MinWidth,
				this._MinHeight,
				this._Md5,
				this._AddTime,
				this._ProId,
				this._Tag,
				this._Type};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Product_Image");
			/// <summary>
			/// 自增Id
			/// </summary>
			public readonly static Field Id = new Field("Id","Product_Image","自增Id");
			/// <summary>
			/// 图片路径
			/// </summary>
			public readonly static Field ImagePath = new Field("ImagePath","Product_Image","图片路径");
			/// <summary>
			/// 图片格式
			/// </summary>
			public readonly static Field ImageExt = new Field("ImageExt","Product_Image","图片格式");
			/// <summary>
			/// 文件大小
			/// </summary>
			public readonly static Field FileSize = new Field("FileSize","Product_Image","文件大小");
			/// <summary>
			/// 最小宽度
			/// </summary>
			public readonly static Field SmallWidth = new Field("SmallWidth","Product_Image","最小宽度");
			/// <summary>
			/// 最小高度
			/// </summary>
			public readonly static Field SmailHeight = new Field("SmailHeight","Product_Image","最小高度");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MiddleWidth = new Field("MiddleWidth","Product_Image","MiddleWidth");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MiddleHeight = new Field("MiddleHeight","Product_Image","MiddleHeight");
			/// <summary>
			/// 最大宽度
			/// </summary>
			public readonly static Field BigWidth = new Field("BigWidth","Product_Image","最大宽度");
			/// <summary>
			/// 最大高度
			/// </summary>
			public readonly static Field BigHeight = new Field("BigHeight","Product_Image","最大高度");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MinWidth = new Field("MinWidth","Product_Image","MinWidth");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MinHeight = new Field("MinHeight","Product_Image","MinHeight");
			/// <summary>
			/// 文件MD5
			/// </summary>
			public readonly static Field Md5 = new Field("Md5","Product_Image","文件MD5");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AddTime = new Field("AddTime","Product_Image","AddTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ProId = new Field("ProId","Product_Image","ProId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Tag = new Field("Tag","Product_Image","Tag");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Type = new Field("Type","Product_Image","Type");
		}
		#endregion


	}
}

