//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace FancyFix.OA.Model
{

	/// <summary>
	/// 实体类Questionnaire_Answerer 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Questionnaire_Answerer")]
	[Serializable]
	public partial class Questionnaire_Answerer : Entity 
	{
		#region Model
		private int _Id;
		private string _Name;
		private int? _SubjectId;
		private string _Tel;
		private string _Email;
		private string _Company;
		private int? _WxId;
		private string _WxName;
		private DateTime? _AddTime;
		private DateTime? _StartTime;
		private int? _Score;
		private int? _CorrectNum;
		private string _DISC;
		private bool? _IsDISC;
		private string _Job;
		private string _Department;
		private bool? _IsMobile;
		private string _UserAgent;
		private string _IP;
		private string _Country;
		private string _Area;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? SubjectId
		{
			get{ return _SubjectId; }
			set
			{
				this.OnPropertyValueChange(_.SubjectId,_SubjectId,value);
				this._SubjectId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Tel
		{
			get{ return _Tel; }
			set
			{
				this.OnPropertyValueChange(_.Tel,_Tel,value);
				this._Tel=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Email
		{
			get{ return _Email; }
			set
			{
				this.OnPropertyValueChange(_.Email,_Email,value);
				this._Email=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Company
		{
			get{ return _Company; }
			set
			{
				this.OnPropertyValueChange(_.Company,_Company,value);
				this._Company=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? WxId
		{
			get{ return _WxId; }
			set
			{
				this.OnPropertyValueChange(_.WxId,_WxId,value);
				this._WxId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string WxName
		{
			get{ return _WxName; }
			set
			{
				this.OnPropertyValueChange(_.WxName,_WxName,value);
				this._WxName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? AddTime
		{
			get{ return _AddTime; }
			set
			{
				this.OnPropertyValueChange(_.AddTime,_AddTime,value);
				this._AddTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? StartTime
		{
			get{ return _StartTime; }
			set
			{
				this.OnPropertyValueChange(_.StartTime,_StartTime,value);
				this._StartTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Score
		{
			get{ return _Score; }
			set
			{
				this.OnPropertyValueChange(_.Score,_Score,value);
				this._Score=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CorrectNum
		{
			get{ return _CorrectNum; }
			set
			{
				this.OnPropertyValueChange(_.CorrectNum,_CorrectNum,value);
				this._CorrectNum=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string DISC
		{
			get{ return _DISC; }
			set
			{
				this.OnPropertyValueChange(_.DISC,_DISC,value);
				this._DISC=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool? IsDISC
		{
			get{ return _IsDISC; }
			set
			{
				this.OnPropertyValueChange(_.IsDISC,_IsDISC,value);
				this._IsDISC=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Job
		{
			get{ return _Job; }
			set
			{
				this.OnPropertyValueChange(_.Job,_Job,value);
				this._Job=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Department
		{
			get{ return _Department; }
			set
			{
				this.OnPropertyValueChange(_.Department,_Department,value);
				this._Department=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool? IsMobile
		{
			get{ return _IsMobile; }
			set
			{
				this.OnPropertyValueChange(_.IsMobile,_IsMobile,value);
				this._IsMobile=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string UserAgent
		{
			get{ return _UserAgent; }
			set
			{
				this.OnPropertyValueChange(_.UserAgent,_UserAgent,value);
				this._UserAgent=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string IP
		{
			get{ return _IP; }
			set
			{
				this.OnPropertyValueChange(_.IP,_IP,value);
				this._IP=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Country
		{
			get{ return _Country; }
			set
			{
				this.OnPropertyValueChange(_.Country,_Country,value);
				this._Country=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Area
		{
			get{ return _Area; }
			set
			{
				this.OnPropertyValueChange(_.Area,_Area,value);
				this._Area=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Name,
				_.SubjectId,
				_.Tel,
				_.Email,
				_.Company,
				_.WxId,
				_.WxName,
				_.AddTime,
				_.StartTime,
				_.Score,
				_.CorrectNum,
				_.DISC,
				_.IsDISC,
				_.Job,
				_.Department,
				_.IsMobile,
				_.UserAgent,
				_.IP,
				_.Country,
				_.Area};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Name,
				this._SubjectId,
				this._Tel,
				this._Email,
				this._Company,
				this._WxId,
				this._WxName,
				this._AddTime,
				this._StartTime,
				this._Score,
				this._CorrectNum,
				this._DISC,
				this._IsDISC,
				this._Job,
				this._Department,
				this._IsMobile,
				this._UserAgent,
				this._IP,
				this._Country,
				this._Area};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Questionnaire_Answerer");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Questionnaire_Answerer","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name","Questionnaire_Answerer","Name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SubjectId = new Field("SubjectId","Questionnaire_Answerer","SubjectId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Tel = new Field("Tel","Questionnaire_Answerer","Tel");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Email = new Field("Email","Questionnaire_Answerer","Email");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Company = new Field("Company","Questionnaire_Answerer","Company");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field WxId = new Field("WxId","Questionnaire_Answerer","WxId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field WxName = new Field("WxName","Questionnaire_Answerer","WxName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AddTime = new Field("AddTime","Questionnaire_Answerer","AddTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StartTime = new Field("StartTime","Questionnaire_Answerer","StartTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Score = new Field("Score","Questionnaire_Answerer","Score");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CorrectNum = new Field("CorrectNum","Questionnaire_Answerer","CorrectNum");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DISC = new Field("DISC","Questionnaire_Answerer","DISC");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsDISC = new Field("IsDISC","Questionnaire_Answerer","IsDISC");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Job = new Field("Job","Questionnaire_Answerer","Job");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Department = new Field("Department","Questionnaire_Answerer","Department");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsMobile = new Field("IsMobile","Questionnaire_Answerer","IsMobile");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UserAgent = new Field("UserAgent","Questionnaire_Answerer","UserAgent");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IP = new Field("IP","Questionnaire_Answerer","IP");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Country = new Field("Country","Questionnaire_Answerer","Country");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Area = new Field("Area","Questionnaire_Answerer","Area");
		}
		#endregion


	}
}

