//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace FancyFix.OA.Model
{

	/// <summary>
	/// 实体类Questionnaire_DISC 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Questionnaire_DISC")]
	[Serializable]
	public partial class Questionnaire_DISC : Entity 
	{
		#region Model
		private int _Id;
		private string _D;
		private string _I;
		private string _S;
		private string _C;
		private int? _Sequence;
		private bool? _IsShow;
		private string _DISC;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string D
		{
			get{ return _D; }
			set
			{
				this.OnPropertyValueChange(_.D,_D,value);
				this._D=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string I
		{
			get{ return _I; }
			set
			{
				this.OnPropertyValueChange(_.I,_I,value);
				this._I=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string S
		{
			get{ return _S; }
			set
			{
				this.OnPropertyValueChange(_.S,_S,value);
				this._S=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string C
		{
			get{ return _C; }
			set
			{
				this.OnPropertyValueChange(_.C,_C,value);
				this._C=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Sequence
		{
			get{ return _Sequence; }
			set
			{
				this.OnPropertyValueChange(_.Sequence,_Sequence,value);
				this._Sequence=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool? IsShow
		{
			get{ return _IsShow; }
			set
			{
				this.OnPropertyValueChange(_.IsShow,_IsShow,value);
				this._IsShow=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string DISC
		{
			get{ return _DISC; }
			set
			{
				this.OnPropertyValueChange(_.DISC,_DISC,value);
				this._DISC=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.D,
				_.I,
				_.S,
				_.C,
				_.Sequence,
				_.IsShow,
				_.DISC};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._D,
				this._I,
				this._S,
				this._C,
				this._Sequence,
				this._IsShow,
				this._DISC};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Questionnaire_DISC");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Questionnaire_DISC","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field D = new Field("D","Questionnaire_DISC","D");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field I = new Field("I","Questionnaire_DISC","I");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field S = new Field("S","Questionnaire_DISC","S");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field C = new Field("C","Questionnaire_DISC","C");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Sequence = new Field("Sequence","Questionnaire_DISC","Sequence");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsShow = new Field("IsShow","Questionnaire_DISC","IsShow");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DISC = new Field("DISC","Questionnaire_DISC","DISC");
		}
		#endregion


	}
}

