//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace FancyFix.OA.Model
{

	/// <summary>
	/// 实体类Questionnaire_Info 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Questionnaire_Info")]
	[Serializable]
	public partial class Questionnaire_Info : Entity 
	{
		#region Model
		private int _Id;
		private int? _SubjectId;
		private string _Title;
		private int? _Type;
		private string _Options;
		private string _Answer;
		private int? _Sequence;
		private string _Remark;
		private int? _Score;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? SubjectId
		{
			get{ return _SubjectId; }
			set
			{
				this.OnPropertyValueChange(_.SubjectId,_SubjectId,value);
				this._SubjectId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Title
		{
			get{ return _Title; }
			set
			{
				this.OnPropertyValueChange(_.Title,_Title,value);
				this._Title=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Type
		{
			get{ return _Type; }
			set
			{
				this.OnPropertyValueChange(_.Type,_Type,value);
				this._Type=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Options
		{
			get{ return _Options; }
			set
			{
				this.OnPropertyValueChange(_.Options,_Options,value);
				this._Options=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Answer
		{
			get{ return _Answer; }
			set
			{
				this.OnPropertyValueChange(_.Answer,_Answer,value);
				this._Answer=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Sequence
		{
			get{ return _Sequence; }
			set
			{
				this.OnPropertyValueChange(_.Sequence,_Sequence,value);
				this._Sequence=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange(_.Remark,_Remark,value);
				this._Remark=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Score
		{
			get{ return _Score; }
			set
			{
				this.OnPropertyValueChange(_.Score,_Score,value);
				this._Score=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.SubjectId,
				_.Title,
				_.Type,
				_.Options,
				_.Answer,
				_.Sequence,
				_.Remark,
				_.Score};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._SubjectId,
				this._Title,
				this._Type,
				this._Options,
				this._Answer,
				this._Sequence,
				this._Remark,
				this._Score};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Questionnaire_Info");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Questionnaire_Info","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SubjectId = new Field("SubjectId","Questionnaire_Info","SubjectId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Title = new Field("Title","Questionnaire_Info","Title");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Type = new Field("Type","Questionnaire_Info","Type");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Options = new Field("Options","Questionnaire_Info","Options");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Answer = new Field("Answer","Questionnaire_Info","Answer");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Sequence = new Field("Sequence","Questionnaire_Info","Sequence");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Remark = new Field("Remark","Questionnaire_Info","Remark");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Score = new Field("Score","Questionnaire_Info","Score");
		}
		#endregion


	}
}

