//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace FancyFix.OA.Model
{

	/// <summary>
	/// 实体类Supplier_List 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Supplier_List")]
	[Serializable]
	public partial class Supplier_List : Entity 
	{
		#region Model
		private int _Id;
		private string _Code;
		private string _Name;
		private int? _SupplierType;
		private string _BusinessScope;
		private string _Contact1;
		private string _Contact2;
		private string _Site;
		private string _Address;
		private DateTime? _StartDate;
		private DateTime? _EndDate;
		private int? _LabelId;
		private string _Note;
		private string _SupplierAb;
		private DateTime? _AddDate;
		private string _AccountDate;
		private int? _AddUserId;
		private DateTime? _LastDate;
		private int? _LastUserId;
		private int? _Display;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 供应商代码
		/// </summary>
		public string Code
		{
			get{ return _Code; }
			set
			{
				this.OnPropertyValueChange(_.Code,_Code,value);
				this._Code=value;
			}
		}
		/// <summary>
		/// 供应商名称
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 供应商类型
		/// </summary>
		public int? SupplierType
		{
			get{ return _SupplierType; }
			set
			{
				this.OnPropertyValueChange(_.SupplierType,_SupplierType,value);
				this._SupplierType=value;
			}
		}
		/// <summary>
		/// 经营范围
		/// </summary>
		public string BusinessScope
		{
			get{ return _BusinessScope; }
			set
			{
				this.OnPropertyValueChange(_.BusinessScope,_BusinessScope,value);
				this._BusinessScope=value;
			}
		}
		/// <summary>
		/// 联系人1
		/// </summary>
		public string Contact1
		{
			get{ return _Contact1; }
			set
			{
				this.OnPropertyValueChange(_.Contact1,_Contact1,value);
				this._Contact1=value;
			}
		}
		/// <summary>
		/// 联系人2
		/// </summary>
		public string Contact2
		{
			get{ return _Contact2; }
			set
			{
				this.OnPropertyValueChange(_.Contact2,_Contact2,value);
				this._Contact2=value;
			}
		}
		/// <summary>
		/// 网址
		/// </summary>
		public string Site
		{
			get{ return _Site; }
			set
			{
				this.OnPropertyValueChange(_.Site,_Site,value);
				this._Site=value;
			}
		}
		/// <summary>
		/// 地址
		/// </summary>
		public string Address
		{
			get{ return _Address; }
			set
			{
				this.OnPropertyValueChange(_.Address,_Address,value);
				this._Address=value;
			}
		}
		/// <summary>
		/// 开始时间
		/// </summary>
		public DateTime? StartDate
		{
			get{ return _StartDate; }
			set
			{
				this.OnPropertyValueChange(_.StartDate,_StartDate,value);
				this._StartDate=value;
			}
		}
		/// <summary>
		/// 结束时间
		/// </summary>
		public DateTime? EndDate
		{
			get{ return _EndDate; }
			set
			{
				this.OnPropertyValueChange(_.EndDate,_EndDate,value);
				this._EndDate=value;
			}
		}
		/// <summary>
		/// 供应商标签
		/// </summary>
		public int? LabelId
		{
			get{ return _LabelId; }
			set
			{
				this.OnPropertyValueChange(_.LabelId,_LabelId,value);
				this._LabelId=value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		public string Note
		{
			get{ return _Note; }
			set
			{
				this.OnPropertyValueChange(_.Note,_Note,value);
				this._Note=value;
			}
		}
		/// <summary>
		/// 供应商名称缩写
		/// </summary>
		public string SupplierAb
		{
			get{ return _SupplierAb; }
			set
			{
				this.OnPropertyValueChange(_.SupplierAb,_SupplierAb,value);
				this._SupplierAb=value;
			}
		}
		/// <summary>
		/// 添加时间
		/// </summary>
		public DateTime? AddDate
		{
			get{ return _AddDate; }
			set
			{
				this.OnPropertyValueChange(_.AddDate,_AddDate,value);
				this._AddDate=value;
			}
		}
		/// <summary>
		/// 账期
		/// </summary>
		public string AccountDate
		{
			get{ return _AccountDate; }
			set
			{
				this.OnPropertyValueChange(_.AccountDate,_AccountDate,value);
				this._AccountDate=value;
			}
		}
		/// <summary>
		/// 添加人
		/// </summary>
		public int? AddUserId
		{
			get{ return _AddUserId; }
			set
			{
				this.OnPropertyValueChange(_.AddUserId,_AddUserId,value);
				this._AddUserId=value;
			}
		}
		/// <summary>
		/// 最后修改时间
		/// </summary>
		public DateTime? LastDate
		{
			get{ return _LastDate; }
			set
			{
				this.OnPropertyValueChange(_.LastDate,_LastDate,value);
				this._LastDate=value;
			}
		}
		/// <summary>
		/// 最后修改人
		/// </summary>
		public int? LastUserId
		{
			get{ return _LastUserId; }
			set
			{
				this.OnPropertyValueChange(_.LastUserId,_LastUserId,value);
				this._LastUserId=value;
			}
		}
		/// <summary>
		/// _1：显示，2：隐藏
		/// </summary>
		public int? Display
		{
			get{ return _Display; }
			set
			{
				this.OnPropertyValueChange(_.Display,_Display,value);
				this._Display=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Code,
				_.Name,
				_.SupplierType,
				_.BusinessScope,
				_.Contact1,
				_.Contact2,
				_.Site,
				_.Address,
				_.StartDate,
				_.EndDate,
				_.LabelId,
				_.Note,
				_.SupplierAb,
				_.AddDate,
				_.AccountDate,
				_.AddUserId,
				_.LastDate,
				_.LastUserId,
				_.Display};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Code,
				this._Name,
				this._SupplierType,
				this._BusinessScope,
				this._Contact1,
				this._Contact2,
				this._Site,
				this._Address,
				this._StartDate,
				this._EndDate,
				this._LabelId,
				this._Note,
				this._SupplierAb,
				this._AddDate,
				this._AccountDate,
				this._AddUserId,
				this._LastDate,
				this._LastUserId,
				this._Display};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Supplier_List");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Supplier_List","Id");
			/// <summary>
			/// 供应商代码
			/// </summary>
			public readonly static Field Code = new Field("Code","Supplier_List","供应商代码");
			/// <summary>
			/// 供应商名称
			/// </summary>
			public readonly static Field Name = new Field("Name","Supplier_List","供应商名称");
			/// <summary>
			/// 供应商类型
			/// </summary>
			public readonly static Field SupplierType = new Field("SupplierType","Supplier_List","供应商类型");
			/// <summary>
			/// 经营范围
			/// </summary>
			public readonly static Field BusinessScope = new Field("BusinessScope","Supplier_List","经营范围");
			/// <summary>
			/// 联系人1
			/// </summary>
			public readonly static Field Contact1 = new Field("Contact1","Supplier_List","联系人1");
			/// <summary>
			/// 联系人2
			/// </summary>
			public readonly static Field Contact2 = new Field("Contact2","Supplier_List","联系人2");
			/// <summary>
			/// 网址
			/// </summary>
			public readonly static Field Site = new Field("Site","Supplier_List","网址");
			/// <summary>
			/// 地址
			/// </summary>
			public readonly static Field Address = new Field("Address","Supplier_List","地址");
			/// <summary>
			/// 开始时间
			/// </summary>
			public readonly static Field StartDate = new Field("StartDate","Supplier_List","开始时间");
			/// <summary>
			/// 结束时间
			/// </summary>
			public readonly static Field EndDate = new Field("EndDate","Supplier_List","结束时间");
			/// <summary>
			/// 供应商标签
			/// </summary>
			public readonly static Field LabelId = new Field("LabelId","Supplier_List","供应商标签");
			/// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Note = new Field("Note","Supplier_List","备注");
			/// <summary>
			/// 供应商名称缩写
			/// </summary>
			public readonly static Field SupplierAb = new Field("SupplierAb","Supplier_List","供应商名称缩写");
			/// <summary>
			/// 添加时间
			/// </summary>
			public readonly static Field AddDate = new Field("AddDate","Supplier_List","添加时间");
			/// <summary>
			/// 账期
			/// </summary>
			public readonly static Field AccountDate = new Field("AccountDate","Supplier_List","账期");
			/// <summary>
			/// 添加人
			/// </summary>
			public readonly static Field AddUserId = new Field("AddUserId","Supplier_List","添加人");
			/// <summary>
			/// 最后修改时间
			/// </summary>
			public readonly static Field LastDate = new Field("LastDate","Supplier_List","最后修改时间");
			/// <summary>
			/// 最后修改人
			/// </summary>
			public readonly static Field LastUserId = new Field("LastUserId","Supplier_List","最后修改人");
			/// <summary>
			/// _1：显示，2：隐藏
			/// </summary>
			public readonly static Field Display = new Field("Display","Supplier_List","_1：显示，2：隐藏");
		}
		#endregion


	}
}

