//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace FancyFix.OA.Model
{

	/// <summary>
	/// 实体类Supplier_PriceMapping 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Supplier_PriceMapping")]
	[Serializable]
	public partial class Supplier_PriceMapping : Entity 
	{
		#region Model
		private int _Id;
		private string _RawMaterialCode;
		private string _VendorCode;
		private DateTime? _AddDate;
		private int? _AddUserId;
		private DateTime? _LastDate;
		private int? _LastUserId;
		private int? _Display;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 原材料ID
		/// </summary>
		public string RawMaterialCode
		{
			get{ return _RawMaterialCode; }
			set
			{
				this.OnPropertyValueChange(_.RawMaterialCode,_RawMaterialCode,value);
				this._RawMaterialCode=value;
			}
		}
		/// <summary>
		/// 供应商ID
		/// </summary>
		public string VendorCode
		{
			get{ return _VendorCode; }
			set
			{
				this.OnPropertyValueChange(_.VendorCode,_VendorCode,value);
				this._VendorCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? AddDate
		{
			get{ return _AddDate; }
			set
			{
				this.OnPropertyValueChange(_.AddDate,_AddDate,value);
				this._AddDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? AddUserId
		{
			get{ return _AddUserId; }
			set
			{
				this.OnPropertyValueChange(_.AddUserId,_AddUserId,value);
				this._AddUserId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? LastDate
		{
			get{ return _LastDate; }
			set
			{
				this.OnPropertyValueChange(_.LastDate,_LastDate,value);
				this._LastDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? LastUserId
		{
			get{ return _LastUserId; }
			set
			{
				this.OnPropertyValueChange(_.LastUserId,_LastUserId,value);
				this._LastUserId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Display
		{
			get{ return _Display; }
			set
			{
				this.OnPropertyValueChange(_.Display,_Display,value);
				this._Display=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.RawMaterialCode,
				_.VendorCode,
				_.AddDate,
				_.AddUserId,
				_.LastDate,
				_.LastUserId,
				_.Display};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._RawMaterialCode,
				this._VendorCode,
				this._AddDate,
				this._AddUserId,
				this._LastDate,
				this._LastUserId,
				this._Display};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Supplier_PriceMapping");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Supplier_PriceMapping","Id");
			/// <summary>
			/// 原材料ID
			/// </summary>
			public readonly static Field RawMaterialCode = new Field("RawMaterialCode","Supplier_PriceMapping","原材料ID");
			/// <summary>
			/// 供应商ID
			/// </summary>
			public readonly static Field VendorCode = new Field("VendorCode","Supplier_PriceMapping","供应商ID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AddDate = new Field("AddDate","Supplier_PriceMapping","AddDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AddUserId = new Field("AddUserId","Supplier_PriceMapping","AddUserId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastDate = new Field("LastDate","Supplier_PriceMapping","LastDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastUserId = new Field("LastUserId","Supplier_PriceMapping","LastUserId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Display = new Field("Display","Supplier_PriceMapping","Display");
		}
		#endregion


	}
}

