//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace FancyFix.OA.Model
{

	/// <summary>
	/// 实体类Supplier_VendorInfo 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Supplier_VendorInfo")]
	[Serializable]
	public partial class Supplier_VendorInfo : Entity 
	{
		#region Model
		private int _Id;
		private int? _VendorId;
		private string _Owners;
		private string _TableNumber;
		private string _Version;
		private DateTime? _EffectiveDate;
		private int? _VersionType;
		private DateTime? _WriteDate;
		private string _CompanyEnglishName;
		private string _PostCode1;
		private string _PurchaseOrderAddressedTo;
		private string _PostCode2;
		private string _FaxNumber;
		private string _EmailForPO;
		private string _TaxNumber;
		private string _TaxRate;
		private string _OrderCurrency;
		private string _PaymentTerms;
		private string _Incoterms;
		private string _BankKey;
		private string _SwiftCode;
		private string _NameOfBank;
		private string _ACNo;
		private int? _FormOfBusiness;
		private string _BusinessRegistrationNumber;
		private string _RegisteredCapital;
		private string _CertificateOfCorporation;
		private string _ProductsOrServiceSales;
		private int? _MOQ;
		private string _LeadTime;
		private string _ManagementMenberName1;
		private string _ManagementMenberTitle1;
		private string _ManagementMenberName2;
		private string _ManagementMenberTitle2;
		private string _ManagementMenberName3;
		private string _ManagementMenberTitle3;
		private string _ManagementMenberName4;
		private string _ManagementMenberTitle4;
		private string _ContactPersonsName1;
		private string _ContactPersonsTitle1;
		private string _ContactPersonsTel1;
		private string _ContactPersonsFax1;
		private string _ContactPersonsEmail1;
		private string _ContactPersonsName2;
		private string _ContactPersonsTitle2;
		private string _ContactPersonsTel2;
		private string _ContactPersonsFax2;
		private string _ContactPersonsEmail2;
		private DateTime? _AddDate;
		private int? _AddUserId;
		private DateTime? _LastDate;
		private int? _LastUserId;
		private int? _Dispaly;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 供应商Id
		/// </summary>
		public int? VendorId
		{
			get{ return _VendorId; }
			set
			{
				this.OnPropertyValueChange(_.VendorId,_VendorId,value);
				this._VendorId=value;
			}
		}
		/// <summary>
		/// 所有者
		/// </summary>
		public string Owners
		{
			get{ return _Owners; }
			set
			{
				this.OnPropertyValueChange(_.Owners,_Owners,value);
				this._Owners=value;
			}
		}
		/// <summary>
		/// 表格编号
		/// </summary>
		public string TableNumber
		{
			get{ return _TableNumber; }
			set
			{
				this.OnPropertyValueChange(_.TableNumber,_TableNumber,value);
				this._TableNumber=value;
			}
		}
		/// <summary>
		/// 版本号
		/// </summary>
		public string Version
		{
			get{ return _Version; }
			set
			{
				this.OnPropertyValueChange(_.Version,_Version,value);
				this._Version=value;
			}
		}
		/// <summary>
		/// 生效日期
		/// </summary>
		public DateTime? EffectiveDate
		{
			get{ return _EffectiveDate; }
			set
			{
				this.OnPropertyValueChange(_.EffectiveDate,_EffectiveDate,value);
				this._EffectiveDate=value;
			}
		}
		/// <summary>
		/// 供应商类型
		/// </summary>
		public int? VersionType
		{
			get{ return _VersionType; }
			set
			{
				this.OnPropertyValueChange(_.VersionType,_VersionType,value);
				this._VersionType=value;
			}
		}
		/// <summary>
		/// 填写日期
		/// </summary>
		public DateTime? WriteDate
		{
			get{ return _WriteDate; }
			set
			{
				this.OnPropertyValueChange(_.WriteDate,_WriteDate,value);
				this._WriteDate=value;
			}
		}
		/// <summary>
		/// 公司英文名称
		/// </summary>
		public string CompanyEnglishName
		{
			get{ return _CompanyEnglishName; }
			set
			{
				this.OnPropertyValueChange(_.CompanyEnglishName,_CompanyEnglishName,value);
				this._CompanyEnglishName=value;
			}
		}
		/// <summary>
		/// 公司注册地址邮编
		/// </summary>
		public string PostCode1
		{
			get{ return _PostCode1; }
			set
			{
				this.OnPropertyValueChange(_.PostCode1,_PostCode1,value);
				this._PostCode1=value;
			}
		}
		/// <summary>
		/// 合同/订单送达地址
		/// </summary>
		public string PurchaseOrderAddressedTo
		{
			get{ return _PurchaseOrderAddressedTo; }
			set
			{
				this.OnPropertyValueChange(_.PurchaseOrderAddressedTo,_PurchaseOrderAddressedTo,value);
				this._PurchaseOrderAddressedTo=value;
			}
		}
		/// <summary>
		/// 合同/订单送达地址邮编
		/// </summary>
		public string PostCode2
		{
			get{ return _PostCode2; }
			set
			{
				this.OnPropertyValueChange(_.PostCode2,_PostCode2,value);
				this._PostCode2=value;
			}
		}
		/// <summary>
		/// 传真号码
		/// </summary>
		public string FaxNumber
		{
			get{ return _FaxNumber; }
			set
			{
				this.OnPropertyValueChange(_.FaxNumber,_FaxNumber,value);
				this._FaxNumber=value;
			}
		}
		/// <summary>
		/// 订单及日常工作邮箱
		/// </summary>
		public string EmailForPO
		{
			get{ return _EmailForPO; }
			set
			{
				this.OnPropertyValueChange(_.EmailForPO,_EmailForPO,value);
				this._EmailForPO=value;
			}
		}
		/// <summary>
		/// 税号
		/// </summary>
		public string TaxNumber
		{
			get{ return _TaxNumber; }
			set
			{
				this.OnPropertyValueChange(_.TaxNumber,_TaxNumber,value);
				this._TaxNumber=value;
			}
		}
		/// <summary>
		/// 税率
		/// </summary>
		public string TaxRate
		{
			get{ return _TaxRate; }
			set
			{
				this.OnPropertyValueChange(_.TaxRate,_TaxRate,value);
				this._TaxRate=value;
			}
		}
		/// <summary>
		/// 交易币种
		/// </summary>
		public string OrderCurrency
		{
			get{ return _OrderCurrency; }
			set
			{
				this.OnPropertyValueChange(_.OrderCurrency,_OrderCurrency,value);
				this._OrderCurrency=value;
			}
		}
		/// <summary>
		/// 付款条件
		/// </summary>
		public string PaymentTerms
		{
			get{ return _PaymentTerms; }
			set
			{
				this.OnPropertyValueChange(_.PaymentTerms,_PaymentTerms,value);
				this._PaymentTerms=value;
			}
		}
		/// <summary>
		/// 交易方式
		/// </summary>
		public string Incoterms
		{
			get{ return _Incoterms; }
			set
			{
				this.OnPropertyValueChange(_.Incoterms,_Incoterms,value);
				this._Incoterms=value;
			}
		}
		/// <summary>
		/// 开户行行号
		/// </summary>
		public string BankKey
		{
			get{ return _BankKey; }
			set
			{
				this.OnPropertyValueChange(_.BankKey,_BankKey,value);
				this._BankKey=value;
			}
		}
		/// <summary>
		/// 银行国际代码
		/// </summary>
		public string SwiftCode
		{
			get{ return _SwiftCode; }
			set
			{
				this.OnPropertyValueChange(_.SwiftCode,_SwiftCode,value);
				this._SwiftCode=value;
			}
		}
		/// <summary>
		/// 开户行名称
		/// </summary>
		public string NameOfBank
		{
			get{ return _NameOfBank; }
			set
			{
				this.OnPropertyValueChange(_.NameOfBank,_NameOfBank,value);
				this._NameOfBank=value;
			}
		}
		/// <summary>
		/// 银行账号
		/// </summary>
		public string ACNo
		{
			get{ return _ACNo; }
			set
			{
				this.OnPropertyValueChange(_.ACNo,_ACNo,value);
				this._ACNo=value;
			}
		}
		/// <summary>
		/// 公司性质
		/// </summary>
		public int? FormOfBusiness
		{
			get{ return _FormOfBusiness; }
			set
			{
				this.OnPropertyValueChange(_.FormOfBusiness,_FormOfBusiness,value);
				this._FormOfBusiness=value;
			}
		}
		/// <summary>
		/// 公司注册码
		/// </summary>
		public string BusinessRegistrationNumber
		{
			get{ return _BusinessRegistrationNumber; }
			set
			{
				this.OnPropertyValueChange(_.BusinessRegistrationNumber,_BusinessRegistrationNumber,value);
				this._BusinessRegistrationNumber=value;
			}
		}
		/// <summary>
		/// 注册资金
		/// </summary>
		public string RegisteredCapital
		{
			get{ return _RegisteredCapital; }
			set
			{
				this.OnPropertyValueChange(_.RegisteredCapital,_RegisteredCapital,value);
				this._RegisteredCapital=value;
			}
		}
		/// <summary>
		/// 资质文件
		/// </summary>
		public string CertificateOfCorporation
		{
			get{ return _CertificateOfCorporation; }
			set
			{
				this.OnPropertyValueChange(_.CertificateOfCorporation,_CertificateOfCorporation,value);
				this._CertificateOfCorporation=value;
			}
		}
		/// <summary>
		/// 交易的产品或服务名称
		/// </summary>
		public string ProductsOrServiceSales
		{
			get{ return _ProductsOrServiceSales; }
			set
			{
				this.OnPropertyValueChange(_.ProductsOrServiceSales,_ProductsOrServiceSales,value);
				this._ProductsOrServiceSales=value;
			}
		}
		/// <summary>
		/// 最小订购量
		/// </summary>
		public int? MOQ
		{
			get{ return _MOQ; }
			set
			{
				this.OnPropertyValueChange(_.MOQ,_MOQ,value);
				this._MOQ=value;
			}
		}
		/// <summary>
		/// 交货周期
		/// </summary>
		public string LeadTime
		{
			get{ return _LeadTime; }
			set
			{
				this.OnPropertyValueChange(_.LeadTime,_LeadTime,value);
				this._LeadTime=value;
			}
		}
		/// <summary>
		/// 主要负责人1
		/// </summary>
		public string ManagementMenberName1
		{
			get{ return _ManagementMenberName1; }
			set
			{
				this.OnPropertyValueChange(_.ManagementMenberName1,_ManagementMenberName1,value);
				this._ManagementMenberName1=value;
			}
		}
		/// <summary>
		/// 主要负责人职位1
		/// </summary>
		public string ManagementMenberTitle1
		{
			get{ return _ManagementMenberTitle1; }
			set
			{
				this.OnPropertyValueChange(_.ManagementMenberTitle1,_ManagementMenberTitle1,value);
				this._ManagementMenberTitle1=value;
			}
		}
		/// <summary>
		/// 主要负责人2
		/// </summary>
		public string ManagementMenberName2
		{
			get{ return _ManagementMenberName2; }
			set
			{
				this.OnPropertyValueChange(_.ManagementMenberName2,_ManagementMenberName2,value);
				this._ManagementMenberName2=value;
			}
		}
		/// <summary>
		/// 主要负责人职位2
		/// </summary>
		public string ManagementMenberTitle2
		{
			get{ return _ManagementMenberTitle2; }
			set
			{
				this.OnPropertyValueChange(_.ManagementMenberTitle2,_ManagementMenberTitle2,value);
				this._ManagementMenberTitle2=value;
			}
		}
		/// <summary>
		/// 主要负责人3
		/// </summary>
		public string ManagementMenberName3
		{
			get{ return _ManagementMenberName3; }
			set
			{
				this.OnPropertyValueChange(_.ManagementMenberName3,_ManagementMenberName3,value);
				this._ManagementMenberName3=value;
			}
		}
		/// <summary>
		/// 主要负责人职位3
		/// </summary>
		public string ManagementMenberTitle3
		{
			get{ return _ManagementMenberTitle3; }
			set
			{
				this.OnPropertyValueChange(_.ManagementMenberTitle3,_ManagementMenberTitle3,value);
				this._ManagementMenberTitle3=value;
			}
		}
		/// <summary>
		/// 主要负责人4
		/// </summary>
		public string ManagementMenberName4
		{
			get{ return _ManagementMenberName4; }
			set
			{
				this.OnPropertyValueChange(_.ManagementMenberName4,_ManagementMenberName4,value);
				this._ManagementMenberName4=value;
			}
		}
		/// <summary>
		/// 主要负责人职位4
		/// </summary>
		public string ManagementMenberTitle4
		{
			get{ return _ManagementMenberTitle4; }
			set
			{
				this.OnPropertyValueChange(_.ManagementMenberTitle4,_ManagementMenberTitle4,value);
				this._ManagementMenberTitle4=value;
			}
		}
		/// <summary>
		/// 其他联系人姓名1
		/// </summary>
		public string ContactPersonsName1
		{
			get{ return _ContactPersonsName1; }
			set
			{
				this.OnPropertyValueChange(_.ContactPersonsName1,_ContactPersonsName1,value);
				this._ContactPersonsName1=value;
			}
		}
		/// <summary>
		/// 其他联系人职位1
		/// </summary>
		public string ContactPersonsTitle1
		{
			get{ return _ContactPersonsTitle1; }
			set
			{
				this.OnPropertyValueChange(_.ContactPersonsTitle1,_ContactPersonsTitle1,value);
				this._ContactPersonsTitle1=value;
			}
		}
		/// <summary>
		/// 其他联系人电话1
		/// </summary>
		public string ContactPersonsTel1
		{
			get{ return _ContactPersonsTel1; }
			set
			{
				this.OnPropertyValueChange(_.ContactPersonsTel1,_ContactPersonsTel1,value);
				this._ContactPersonsTel1=value;
			}
		}
		/// <summary>
		/// 其他联系人传真1
		/// </summary>
		public string ContactPersonsFax1
		{
			get{ return _ContactPersonsFax1; }
			set
			{
				this.OnPropertyValueChange(_.ContactPersonsFax1,_ContactPersonsFax1,value);
				this._ContactPersonsFax1=value;
			}
		}
		/// <summary>
		/// 其他联系人邮箱1
		/// </summary>
		public string ContactPersonsEmail1
		{
			get{ return _ContactPersonsEmail1; }
			set
			{
				this.OnPropertyValueChange(_.ContactPersonsEmail1,_ContactPersonsEmail1,value);
				this._ContactPersonsEmail1=value;
			}
		}
		/// <summary>
		/// 其他联系人姓名2
		/// </summary>
		public string ContactPersonsName2
		{
			get{ return _ContactPersonsName2; }
			set
			{
				this.OnPropertyValueChange(_.ContactPersonsName2,_ContactPersonsName2,value);
				this._ContactPersonsName2=value;
			}
		}
		/// <summary>
		/// 其他联系人职位2
		/// </summary>
		public string ContactPersonsTitle2
		{
			get{ return _ContactPersonsTitle2; }
			set
			{
				this.OnPropertyValueChange(_.ContactPersonsTitle2,_ContactPersonsTitle2,value);
				this._ContactPersonsTitle2=value;
			}
		}
		/// <summary>
		/// 其他联系人电话2
		/// </summary>
		public string ContactPersonsTel2
		{
			get{ return _ContactPersonsTel2; }
			set
			{
				this.OnPropertyValueChange(_.ContactPersonsTel2,_ContactPersonsTel2,value);
				this._ContactPersonsTel2=value;
			}
		}
		/// <summary>
		/// 其他联系人传真2
		/// </summary>
		public string ContactPersonsFax2
		{
			get{ return _ContactPersonsFax2; }
			set
			{
				this.OnPropertyValueChange(_.ContactPersonsFax2,_ContactPersonsFax2,value);
				this._ContactPersonsFax2=value;
			}
		}
		/// <summary>
		/// 其他联系人邮箱2
		/// </summary>
		public string ContactPersonsEmail2
		{
			get{ return _ContactPersonsEmail2; }
			set
			{
				this.OnPropertyValueChange(_.ContactPersonsEmail2,_ContactPersonsEmail2,value);
				this._ContactPersonsEmail2=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? AddDate
		{
			get{ return _AddDate; }
			set
			{
				this.OnPropertyValueChange(_.AddDate,_AddDate,value);
				this._AddDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? AddUserId
		{
			get{ return _AddUserId; }
			set
			{
				this.OnPropertyValueChange(_.AddUserId,_AddUserId,value);
				this._AddUserId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? LastDate
		{
			get{ return _LastDate; }
			set
			{
				this.OnPropertyValueChange(_.LastDate,_LastDate,value);
				this._LastDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? LastUserId
		{
			get{ return _LastUserId; }
			set
			{
				this.OnPropertyValueChange(_.LastUserId,_LastUserId,value);
				this._LastUserId=value;
			}
		}
		/// <summary>
		/// _1显示；2不显示
		/// </summary>
		public int? Dispaly
		{
			get{ return _Dispaly; }
			set
			{
				this.OnPropertyValueChange(_.Dispaly,_Dispaly,value);
				this._Dispaly=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.VendorId,
				_.Owners,
				_.TableNumber,
				_.Version,
				_.EffectiveDate,
				_.VersionType,
				_.WriteDate,
				_.CompanyEnglishName,
				_.PostCode1,
				_.PurchaseOrderAddressedTo,
				_.PostCode2,
				_.FaxNumber,
				_.EmailForPO,
				_.TaxNumber,
				_.TaxRate,
				_.OrderCurrency,
				_.PaymentTerms,
				_.Incoterms,
				_.BankKey,
				_.SwiftCode,
				_.NameOfBank,
				_.ACNo,
				_.FormOfBusiness,
				_.BusinessRegistrationNumber,
				_.RegisteredCapital,
				_.CertificateOfCorporation,
				_.ProductsOrServiceSales,
				_.MOQ,
				_.LeadTime,
				_.ManagementMenberName1,
				_.ManagementMenberTitle1,
				_.ManagementMenberName2,
				_.ManagementMenberTitle2,
				_.ManagementMenberName3,
				_.ManagementMenberTitle3,
				_.ManagementMenberName4,
				_.ManagementMenberTitle4,
				_.ContactPersonsName1,
				_.ContactPersonsTitle1,
				_.ContactPersonsTel1,
				_.ContactPersonsFax1,
				_.ContactPersonsEmail1,
				_.ContactPersonsName2,
				_.ContactPersonsTitle2,
				_.ContactPersonsTel2,
				_.ContactPersonsFax2,
				_.ContactPersonsEmail2,
				_.AddDate,
				_.AddUserId,
				_.LastDate,
				_.LastUserId,
				_.Dispaly};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._VendorId,
				this._Owners,
				this._TableNumber,
				this._Version,
				this._EffectiveDate,
				this._VersionType,
				this._WriteDate,
				this._CompanyEnglishName,
				this._PostCode1,
				this._PurchaseOrderAddressedTo,
				this._PostCode2,
				this._FaxNumber,
				this._EmailForPO,
				this._TaxNumber,
				this._TaxRate,
				this._OrderCurrency,
				this._PaymentTerms,
				this._Incoterms,
				this._BankKey,
				this._SwiftCode,
				this._NameOfBank,
				this._ACNo,
				this._FormOfBusiness,
				this._BusinessRegistrationNumber,
				this._RegisteredCapital,
				this._CertificateOfCorporation,
				this._ProductsOrServiceSales,
				this._MOQ,
				this._LeadTime,
				this._ManagementMenberName1,
				this._ManagementMenberTitle1,
				this._ManagementMenberName2,
				this._ManagementMenberTitle2,
				this._ManagementMenberName3,
				this._ManagementMenberTitle3,
				this._ManagementMenberName4,
				this._ManagementMenberTitle4,
				this._ContactPersonsName1,
				this._ContactPersonsTitle1,
				this._ContactPersonsTel1,
				this._ContactPersonsFax1,
				this._ContactPersonsEmail1,
				this._ContactPersonsName2,
				this._ContactPersonsTitle2,
				this._ContactPersonsTel2,
				this._ContactPersonsFax2,
				this._ContactPersonsEmail2,
				this._AddDate,
				this._AddUserId,
				this._LastDate,
				this._LastUserId,
				this._Dispaly};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Supplier_VendorInfo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Supplier_VendorInfo","Id");
			/// <summary>
			/// 供应商Id
			/// </summary>
			public readonly static Field VendorId = new Field("VendorId","Supplier_VendorInfo","供应商Id");
			/// <summary>
			/// 所有者
			/// </summary>
			public readonly static Field Owners = new Field("Owners","Supplier_VendorInfo","所有者");
			/// <summary>
			/// 表格编号
			/// </summary>
			public readonly static Field TableNumber = new Field("TableNumber","Supplier_VendorInfo","表格编号");
			/// <summary>
			/// 版本号
			/// </summary>
			public readonly static Field Version = new Field("Version","Supplier_VendorInfo","版本号");
			/// <summary>
			/// 生效日期
			/// </summary>
			public readonly static Field EffectiveDate = new Field("EffectiveDate","Supplier_VendorInfo","生效日期");
			/// <summary>
			/// 供应商类型
			/// </summary>
			public readonly static Field VersionType = new Field("VersionType","Supplier_VendorInfo","供应商类型");
			/// <summary>
			/// 填写日期
			/// </summary>
			public readonly static Field WriteDate = new Field("WriteDate","Supplier_VendorInfo","填写日期");
			/// <summary>
			/// 公司英文名称
			/// </summary>
			public readonly static Field CompanyEnglishName = new Field("CompanyEnglishName","Supplier_VendorInfo","公司英文名称");
			/// <summary>
			/// 公司注册地址邮编
			/// </summary>
			public readonly static Field PostCode1 = new Field("PostCode1","Supplier_VendorInfo","公司注册地址邮编");
			/// <summary>
			/// 合同/订单送达地址
			/// </summary>
			public readonly static Field PurchaseOrderAddressedTo = new Field("PurchaseOrderAddressedTo","Supplier_VendorInfo","合同/订单送达地址");
			/// <summary>
			/// 合同/订单送达地址邮编
			/// </summary>
			public readonly static Field PostCode2 = new Field("PostCode2","Supplier_VendorInfo","合同/订单送达地址邮编");
			/// <summary>
			/// 传真号码
			/// </summary>
			public readonly static Field FaxNumber = new Field("FaxNumber","Supplier_VendorInfo","传真号码");
			/// <summary>
			/// 订单及日常工作邮箱
			/// </summary>
			public readonly static Field EmailForPO = new Field("EmailForPO","Supplier_VendorInfo","订单及日常工作邮箱");
			/// <summary>
			/// 税号
			/// </summary>
			public readonly static Field TaxNumber = new Field("TaxNumber","Supplier_VendorInfo","税号");
			/// <summary>
			/// 税率
			/// </summary>
			public readonly static Field TaxRate = new Field("TaxRate","Supplier_VendorInfo","税率");
			/// <summary>
			/// 交易币种
			/// </summary>
			public readonly static Field OrderCurrency = new Field("OrderCurrency","Supplier_VendorInfo","交易币种");
			/// <summary>
			/// 付款条件
			/// </summary>
			public readonly static Field PaymentTerms = new Field("PaymentTerms","Supplier_VendorInfo","付款条件");
			/// <summary>
			/// 交易方式
			/// </summary>
			public readonly static Field Incoterms = new Field("Incoterms","Supplier_VendorInfo","交易方式");
			/// <summary>
			/// 开户行行号
			/// </summary>
			public readonly static Field BankKey = new Field("BankKey","Supplier_VendorInfo","开户行行号");
			/// <summary>
			/// 银行国际代码
			/// </summary>
			public readonly static Field SwiftCode = new Field("SwiftCode","Supplier_VendorInfo","银行国际代码");
			/// <summary>
			/// 开户行名称
			/// </summary>
			public readonly static Field NameOfBank = new Field("NameOfBank","Supplier_VendorInfo","开户行名称");
			/// <summary>
			/// 银行账号
			/// </summary>
			public readonly static Field ACNo = new Field("ACNo","Supplier_VendorInfo","银行账号");
			/// <summary>
			/// 公司性质
			/// </summary>
			public readonly static Field FormOfBusiness = new Field("FormOfBusiness","Supplier_VendorInfo","公司性质");
			/// <summary>
			/// 公司注册码
			/// </summary>
			public readonly static Field BusinessRegistrationNumber = new Field("BusinessRegistrationNumber","Supplier_VendorInfo","公司注册码");
			/// <summary>
			/// 注册资金
			/// </summary>
			public readonly static Field RegisteredCapital = new Field("RegisteredCapital","Supplier_VendorInfo","注册资金");
			/// <summary>
			/// 资质文件
			/// </summary>
			public readonly static Field CertificateOfCorporation = new Field("CertificateOfCorporation","Supplier_VendorInfo","资质文件");
			/// <summary>
			/// 交易的产品或服务名称
			/// </summary>
			public readonly static Field ProductsOrServiceSales = new Field("ProductsOrServiceSales","Supplier_VendorInfo","交易的产品或服务名称");
			/// <summary>
			/// 最小订购量
			/// </summary>
			public readonly static Field MOQ = new Field("MOQ","Supplier_VendorInfo","最小订购量");
			/// <summary>
			/// 交货周期
			/// </summary>
			public readonly static Field LeadTime = new Field("LeadTime","Supplier_VendorInfo","交货周期");
			/// <summary>
			/// 主要负责人1
			/// </summary>
			public readonly static Field ManagementMenberName1 = new Field("ManagementMenberName1","Supplier_VendorInfo","主要负责人1");
			/// <summary>
			/// 主要负责人职位1
			/// </summary>
			public readonly static Field ManagementMenberTitle1 = new Field("ManagementMenberTitle1","Supplier_VendorInfo","主要负责人职位1");
			/// <summary>
			/// 主要负责人2
			/// </summary>
			public readonly static Field ManagementMenberName2 = new Field("ManagementMenberName2","Supplier_VendorInfo","主要负责人2");
			/// <summary>
			/// 主要负责人职位2
			/// </summary>
			public readonly static Field ManagementMenberTitle2 = new Field("ManagementMenberTitle2","Supplier_VendorInfo","主要负责人职位2");
			/// <summary>
			/// 主要负责人3
			/// </summary>
			public readonly static Field ManagementMenberName3 = new Field("ManagementMenberName3","Supplier_VendorInfo","主要负责人3");
			/// <summary>
			/// 主要负责人职位3
			/// </summary>
			public readonly static Field ManagementMenberTitle3 = new Field("ManagementMenberTitle3","Supplier_VendorInfo","主要负责人职位3");
			/// <summary>
			/// 主要负责人4
			/// </summary>
			public readonly static Field ManagementMenberName4 = new Field("ManagementMenberName4","Supplier_VendorInfo","主要负责人4");
			/// <summary>
			/// 主要负责人职位4
			/// </summary>
			public readonly static Field ManagementMenberTitle4 = new Field("ManagementMenberTitle4","Supplier_VendorInfo","主要负责人职位4");
			/// <summary>
			/// 其他联系人姓名1
			/// </summary>
			public readonly static Field ContactPersonsName1 = new Field("ContactPersonsName1","Supplier_VendorInfo","其他联系人姓名1");
			/// <summary>
			/// 其他联系人职位1
			/// </summary>
			public readonly static Field ContactPersonsTitle1 = new Field("ContactPersonsTitle1","Supplier_VendorInfo","其他联系人职位1");
			/// <summary>
			/// 其他联系人电话1
			/// </summary>
			public readonly static Field ContactPersonsTel1 = new Field("ContactPersonsTel1","Supplier_VendorInfo","其他联系人电话1");
			/// <summary>
			/// 其他联系人传真1
			/// </summary>
			public readonly static Field ContactPersonsFax1 = new Field("ContactPersonsFax1","Supplier_VendorInfo","其他联系人传真1");
			/// <summary>
			/// 其他联系人邮箱1
			/// </summary>
			public readonly static Field ContactPersonsEmail1 = new Field("ContactPersonsEmail1","Supplier_VendorInfo","其他联系人邮箱1");
			/// <summary>
			/// 其他联系人姓名2
			/// </summary>
			public readonly static Field ContactPersonsName2 = new Field("ContactPersonsName2","Supplier_VendorInfo","其他联系人姓名2");
			/// <summary>
			/// 其他联系人职位2
			/// </summary>
			public readonly static Field ContactPersonsTitle2 = new Field("ContactPersonsTitle2","Supplier_VendorInfo","其他联系人职位2");
			/// <summary>
			/// 其他联系人电话2
			/// </summary>
			public readonly static Field ContactPersonsTel2 = new Field("ContactPersonsTel2","Supplier_VendorInfo","其他联系人电话2");
			/// <summary>
			/// 其他联系人传真2
			/// </summary>
			public readonly static Field ContactPersonsFax2 = new Field("ContactPersonsFax2","Supplier_VendorInfo","其他联系人传真2");
			/// <summary>
			/// 其他联系人邮箱2
			/// </summary>
			public readonly static Field ContactPersonsEmail2 = new Field("ContactPersonsEmail2","Supplier_VendorInfo","其他联系人邮箱2");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AddDate = new Field("AddDate","Supplier_VendorInfo","AddDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AddUserId = new Field("AddUserId","Supplier_VendorInfo","AddUserId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastDate = new Field("LastDate","Supplier_VendorInfo","LastDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LastUserId = new Field("LastUserId","Supplier_VendorInfo","LastUserId");
			/// <summary>
			/// _1显示；2不显示
			/// </summary>
			public readonly static Field Dispaly = new Field("Dispaly","Supplier_VendorInfo","_1显示；2不显示");
		}
		#endregion


	}
}

