//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace FancyFix.OA.Model
{

	/// <summary>
	/// 实体类Valuable_Records 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Valuable_Records")]
	[Serializable]
	public partial class Valuable_Records : Entity 
	{
		#region Model
		private int _Id;
		private int? _Vid;
		private int? _UserId;
		private int? _Score;
		private int? _ParUserId;
		private string _ParUserName;
		private DateTime? _CreateTime;
		private DateTime? _UpdateTime;
		private DateTime? _ApproveTime;
		private int? _Rank;
		private int? _RankScore;
		private int? _Year;
		private int? _Month;
		private bool? _IsApprove;
		private string _Remark;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Vid
		{
			get{ return _Vid; }
			set
			{
				this.OnPropertyValueChange(_.Vid,_Vid,value);
				this._Vid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? UserId
		{
			get{ return _UserId; }
			set
			{
				this.OnPropertyValueChange(_.UserId,_UserId,value);
				this._UserId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Score
		{
			get{ return _Score; }
			set
			{
				this.OnPropertyValueChange(_.Score,_Score,value);
				this._Score=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ParUserId
		{
			get{ return _ParUserId; }
			set
			{
				this.OnPropertyValueChange(_.ParUserId,_ParUserId,value);
				this._ParUserId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ParUserName
		{
			get{ return _ParUserName; }
			set
			{
				this.OnPropertyValueChange(_.ParUserName,_ParUserName,value);
				this._ParUserName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdateTime
		{
			get{ return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange(_.UpdateTime,_UpdateTime,value);
				this._UpdateTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? ApproveTime
		{
			get{ return _ApproveTime; }
			set
			{
				this.OnPropertyValueChange(_.ApproveTime,_ApproveTime,value);
				this._ApproveTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Rank
		{
			get{ return _Rank; }
			set
			{
				this.OnPropertyValueChange(_.Rank,_Rank,value);
				this._Rank=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? RankScore
		{
			get{ return _RankScore; }
			set
			{
				this.OnPropertyValueChange(_.RankScore,_RankScore,value);
				this._RankScore=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Year
		{
			get{ return _Year; }
			set
			{
				this.OnPropertyValueChange(_.Year,_Year,value);
				this._Year=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Month
		{
			get{ return _Month; }
			set
			{
				this.OnPropertyValueChange(_.Month,_Month,value);
				this._Month=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool? IsApprove
		{
			get{ return _IsApprove; }
			set
			{
				this.OnPropertyValueChange(_.IsApprove,_IsApprove,value);
				this._IsApprove=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange(_.Remark,_Remark,value);
				this._Remark=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Vid,
				_.UserId,
				_.Score,
				_.ParUserId,
				_.ParUserName,
				_.CreateTime,
				_.UpdateTime,
				_.ApproveTime,
				_.Rank,
				_.RankScore,
				_.Year,
				_.Month,
				_.IsApprove,
				_.Remark};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Vid,
				this._UserId,
				this._Score,
				this._ParUserId,
				this._ParUserName,
				this._CreateTime,
				this._UpdateTime,
				this._ApproveTime,
				this._Rank,
				this._RankScore,
				this._Year,
				this._Month,
				this._IsApprove,
				this._Remark};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Valuable_Records");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Valuable_Records","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Vid = new Field("Vid","Valuable_Records","Vid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UserId = new Field("UserId","Valuable_Records","UserId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Score = new Field("Score","Valuable_Records","Score");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ParUserId = new Field("ParUserId","Valuable_Records","ParUserId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ParUserName = new Field("ParUserName","Valuable_Records","ParUserName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","Valuable_Records","CreateTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime","Valuable_Records","UpdateTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ApproveTime = new Field("ApproveTime","Valuable_Records","ApproveTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Rank = new Field("Rank","Valuable_Records","Rank");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RankScore = new Field("RankScore","Valuable_Records","RankScore");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Year = new Field("Year","Valuable_Records","Year");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Month = new Field("Month","Valuable_Records","Month");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsApprove = new Field("IsApprove","Valuable_Records","IsApprove");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Remark = new Field("Remark","Valuable_Records","Remark");
		}
		#endregion


	}
}

