//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace FancyFix.OA.Model
{

	/// <summary>
	/// 实体类Valuable_Sample 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Valuable_Sample")]
	[Serializable]
	public partial class Valuable_Sample : Entity 
	{
		#region Model
		private int _Id;
		private int? _Rid;
		private string _Content;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Rid
		{
			get{ return _Rid; }
			set
			{
				this.OnPropertyValueChange(_.Rid,_Rid,value);
				this._Rid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Content
		{
			get{ return _Content; }
			set
			{
				this.OnPropertyValueChange(_.Content,_Content,value);
				this._Content=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Rid,
				_.Content};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Rid,
				this._Content};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Valuable_Sample");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Valuable_Sample","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Rid = new Field("Rid","Valuable_Sample","Rid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Content = new Field("Content","Valuable_Sample","Content");
		}
		#endregion


	}
}

