//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace FancyFix.OA.Model
{

	/// <summary>
	/// 实体类Web_Error 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Web_Error")]
	[Serializable]
	public partial class Web_Error : Entity 
	{
		#region Model
		private int _Id;
		private DateTime? _Date;
		private string _Thread;
		private string _Level;
		private string _Logger;
		private string _Source;
		private string _Message;
		private string _Exception;
		private string _RequestUrl;
		private string _ClientIp;
		private int? _LoginUserId;
		private string _LoginUserName;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? Date
		{
			get{ return _Date; }
			set
			{
				this.OnPropertyValueChange(_.Date,_Date,value);
				this._Date=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Thread
		{
			get{ return _Thread; }
			set
			{
				this.OnPropertyValueChange(_.Thread,_Thread,value);
				this._Thread=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Level
		{
			get{ return _Level; }
			set
			{
				this.OnPropertyValueChange(_.Level,_Level,value);
				this._Level=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Logger
		{
			get{ return _Logger; }
			set
			{
				this.OnPropertyValueChange(_.Logger,_Logger,value);
				this._Logger=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Source
		{
			get{ return _Source; }
			set
			{
				this.OnPropertyValueChange(_.Source,_Source,value);
				this._Source=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Message
		{
			get{ return _Message; }
			set
			{
				this.OnPropertyValueChange(_.Message,_Message,value);
				this._Message=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Exception
		{
			get{ return _Exception; }
			set
			{
				this.OnPropertyValueChange(_.Exception,_Exception,value);
				this._Exception=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string RequestUrl
		{
			get{ return _RequestUrl; }
			set
			{
				this.OnPropertyValueChange(_.RequestUrl,_RequestUrl,value);
				this._RequestUrl=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ClientIp
		{
			get{ return _ClientIp; }
			set
			{
				this.OnPropertyValueChange(_.ClientIp,_ClientIp,value);
				this._ClientIp=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? LoginUserId
		{
			get{ return _LoginUserId; }
			set
			{
				this.OnPropertyValueChange(_.LoginUserId,_LoginUserId,value);
				this._LoginUserId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string LoginUserName
		{
			get{ return _LoginUserName; }
			set
			{
				this.OnPropertyValueChange(_.LoginUserName,_LoginUserName,value);
				this._LoginUserName=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Date,
				_.Thread,
				_.Level,
				_.Logger,
				_.Source,
				_.Message,
				_.Exception,
				_.RequestUrl,
				_.ClientIp,
				_.LoginUserId,
				_.LoginUserName};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Date,
				this._Thread,
				this._Level,
				this._Logger,
				this._Source,
				this._Message,
				this._Exception,
				this._RequestUrl,
				this._ClientIp,
				this._LoginUserId,
				this._LoginUserName};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Web_Error");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Web_Error","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Date = new Field("Date","Web_Error","Date");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Thread = new Field("Thread","Web_Error","Thread");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Level = new Field("Level","Web_Error","Level");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Logger = new Field("Logger","Web_Error","Logger");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Source = new Field("Source","Web_Error","Source");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Message = new Field("Message","Web_Error","Message");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Exception = new Field("Exception","Web_Error","Exception");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RequestUrl = new Field("RequestUrl","Web_Error","RequestUrl");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ClientIp = new Field("ClientIp","Web_Error","ClientIp");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LoginUserId = new Field("LoginUserId","Web_Error","LoginUserId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LoginUserName = new Field("LoginUserName","Web_Error","LoginUserName");
		}
		#endregion


	}
}

